### ISSUE TITLE
Nextcloud 16 compatibility?

### ISSUE THREAD

**Issue by Gomez** [nextcloud/end_to_end_encryption#108]
Even the stable 16 branch has min/max Nextcloud version 17. Just an error or intended?

**Comment by loxK** [comment]
Weird as this is flagship feature

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage

**Comment by jospoortvliet** [comment]
We'll update this app over the coming weeks. For now, it works if you hit the button to allow installing the untested app in the app store.

**Comment by kyrofa** [comment]
Any update on this issue? Still on track for 16.0.2?

**Comment by TarSzator** [comment]
Can the community get an update when this issue will be resolved?

**Comment by jancborchardt** [comment]
@Gomez @loxK @kyrofa @TarSzator did you test the app on current versions and does it work?

Cause if yes, does anyone of you want to open a pull request to increase the max-version to 17 in the "appinfo/info.xml"? :)

**Comment by the-sane** [comment]
@jancborchardt you mean pull request #107 that was merged on April 12th?

**Comment by jancborchardt** [comment]
@rullzer @MorrisJobke your call on how to proceed. :)

**Comment by TarSzator** [comment]
What can we do to speed up the process here?

**Comment by schiessle** [comment]
This is by intention. Because end-to-end encryption is still in a quite early stage so we thought this extra level of warning is useful at this point in time. If you want to give E2E a try you can just enable the app, there shouldn't be any incompatibilities.

**Comment by loxK** [comment]
It is a weird behavior to use Nextcloud's version compatibility feature to warn users about beta/alpha quality software. Nextcloud should have a way to handle such cases.
