### ISSUE TITLE
Why is this still Alpha code?

### ISSUE THREAD

**Issue by danb35** [nextcloud/end_to_end_encryption#111]
This is probably more of a rant than an issue as such, but why is E2EE still "alpha"?  It's been a headline feature for Nextcloud for the last four major releases (even though it isn't compatible with the current major release as noted in #108).  Client support is spotty and fragile, at best.  You warn in the app store that it isn't to be used with anything important.  Is this an important feature to Nextcloud or not?  If it is, surely four major releases should be enough to get it to a stable, usable state.  If not, they need to stop advertising as though it is.

**Comment by tobiasKaminsky** [comment]
We had a very heavy and long discussion beginning of this year, which resulted it https://github.com/nextcloud/end_to_end_encryption_rfc/pull/40.
We also have a rough roadmap how (and when) to tackle existing bugs, starting with v2 , etc.
As far as I remember plan is to have at end of this year a full working version.

**Comment by DiabolusExMachina** [comment]
@tobiasKaminsky Is it possible to follow the progress somehow? 

This is a very important feature and the current version of end to end encryption is not working overall due to severe bugs...

**Comment by GoetheG** [comment]
I really don’t understand that. Nextcloud is a serious institution. Why is it announcing stuff it won’t work on later?

The Nextcloud people published a statement about a Rocket.Chat cooperation – then nothing happened. End-to-end-encryption was introduced and it’s still in beta. Collabora Online is still working very weird. There are plenty of apps wich do not work properly. Still, they introduce new functions every few months without thinking about updating the existing ones. So it seems at least.

If that is the case – why does Nextcloud have majour releases multiple times a year? I don’t understand that kind of corporate politics and I find it kinda sad, cause, I really used to love Nextcloud software but I begin to lose faith.

**Comment by xCozmox** [comment]
This feature is somehow mandatory to me! Really hoping it will be on the agenda.

**Comment by anirudhnihalani** [comment]
I am waiting on this feature for buying a subscription from one of the nextcloud providers. Is this feature stable and working now or is it still alpha?

**Comment by JimLoose** [comment]
really important feature!

@tobiasKaminsky any updates?

**Comment by luixxiul** [comment]
Those looking for an alternative I'd recommend [Cryptomator](https://github.com/cryptomator/cryptomator/), which works stable and properly.

**Comment by DominikWA** [comment]
> 
> 
> Those looking for an alternative I'd recommend [Cryptomator](https://github.com/cryptomator/cryptomator/), which works stable and properly.

I can confirm that Cryptomator is working realy good, using it on all platforms

**Comment by trymeouteh** [comment]
Any ETA on this? This should be the #1 priority right now above all else. I do not see Nextcloud as a secure or private cloud storage platform without a functioning E2EE system. Without E2EE, hackers and other bad actors can read the files on your server. I am better off using sync.com or mega until this is resolved.

Security and privacy should be top priority, E2EE is essential for security and privacy.

**Comment by Waked** [comment]
Got here via a link on a website related to privacy tools and feel the need to bump - what is the status of E2EE?

**Comment by jg76379** [comment]
Can we please have an update on this?

The [nextcloud site is still advertising E2E Encryption](https://nextcloud.com/endtoend/) like it is a production-ready feature, yet the app still warns that it is in an alpha state and should not be used in production. I understand that this is a complex feature that takes time to develop but if it is still a ways off from being production ready the main nextcloud site should at least acknowledge that.

**Comment by georgehrke** [comment]
The website you linked clearly states that this feature is in "Currently in testing phase". Nowhere it mentions the words "production ready".

As you can see in this repository and the client repositories, there has been a lot of activity lately. So stay tuned for upcoming releases.

**Comment by georgehrke** [comment]
Please see https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590
