### ISSUE TITLE
After passphrase reinit, folder encrypted with E2EE are not really secured!

### ISSUE THREAD

**Issue by TinTinMar515** [nextcloud/end_to_end_encryption#122]
The solution proposed by jmcclelland in https://github.com/nextcloud/end_to_end_encryption/issues/32 permited to reinit my passphrases with NC 17.0.3 and E2EE 1.3.0

BUT :
The folder that I tried to encrypt is stored in clear in the server data folder.
This is a big security issue because the folder seems encrypted at client side, no way to get it from the web-cli, nor in other device which don't have the passphrase but, in ftp, I can download and open the files stored in... not so much in the e2ee philosophy !?

Client used is ubuntu 2.6.2git

_Originally posted by @TinTinMar515 in https://github.com/nextcloud/end_to_end_encryption/issues/32#issuecomment-583368965_

**Comment by e-alfred** [comment]
Related issue in the desktop client repository: https://github.com/nextcloud/desktop/issues/816

**Comment by georgehrke** [comment]
@TinTinMar515 Can you please confirm that behaviour you describe is indeed only the case for subfolders?

In that case it's a duplicate of nextcloud/desktop#816

**Comment by georgehrke** [comment]
If it's not the case for subfolders, please open a new issue in https://github.com/nextcloud/desktop/, using the issue template.
