### ISSUE TITLE
DO NOT mark it as featured

### ISSUE THREAD

**Issue by BoleynSu** [nextcloud/end_to_end_encryption#124]
The comment for Featured says that the app is ready for production use while in fact it is not!

**Comment by georgehrke** [comment]
App description contains a big warning:

> Provides the necessary endpoint to enable end-to-end encryption. End-to-end encryption is still in alpha state, don't use this in production and only with test data!

**Comment by BoleynSu** [comment]
Isn't this conflict with Featured then? The comment for Featured says that the app is ready for production use. Please change the description of FEATURED or remove the Featured label for this tag.
