### ISSUE TITLE
Enter E2E Passphrase endless loop

### ISSUE THREAD

**Issue by JimLoose** [nextcloud/end_to_end_encryption#136]
Everytime the Nextcloud client is started we get the following window and whatever you enter it ignores it or simply crashs

Nextcloud: 18.0.3
End-to-End Encryption: 1.4.0
Client: Version 2.6.2stable (build 20191224).

<img width="392" alt="Bildschirmfoto 2020-03-26 um 19 54 30" src="https://user-images.githubusercontent.com/195000/77685627-ff2d6300-6f9b-11ea-9bd6-3fc72c5bb598.png">

**Comment by georgehrke** [comment]
Please open this issue in the desktop repo client and fill the entire issue template
