### ISSUE TITLE
Upload file on encrypted folder

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#14]
Return always error 403 (No permission) ... @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
More infos plz...

https://github.com/nextcloud/end_to_end_encryption/blob/master/doc/api.md
shows 3x 403:
- lock file: 403 forbidden: file already locked and by a different client (wrong token)
- unlock file: 403 forbidden: wrong token, you are not allowed to unlock the file
- update meta-data file: 403 forbidden: if the file was not locked or the client send the wrong token

**Comment by marinofaggiana** [comment]
Upload file encrypted inside encrypt folder  : 

Uploading new files

In case a new file is uploaded the client has to do the following steps:

Generate a new 128-bit encryption key for the file and encrypt it using AES/GCM/NoPadding.
OK

Generate a random identifier for the file (e.g. an UUID) and **upload the encrypted file via WebDAV using the random identifier as file ID**

error 403

Add new file to the files array in the metadata file
Update and lock the encrypted folder as described in “Update metadata file”. The latest metadataKey should be used to encrypt the metadata.

**Comment by tobiasKaminsky** [comment]
Have you locked it prior?

**Comment by marinofaggiana** [comment]
? before upload file ? not metadata ... sure ? with the asynchronous upload files of iOS this is bad

this is not correct  ... 

https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md#uploading-new-files

@tobiasKaminsky @schiessle

**Comment by marinofaggiana** [comment]
ping @tobiasKaminsky
