### ISSUE TITLE
Subdirectories not encrypted

### ISSUE THREAD

**Issue by yadayadaydadaa** [nextcloud/end_to_end_encryption#152]
I think I reported this bug a year ago already, but it's not listed as open:

Subdirectories of encrypted directories are still not encrypted (macOS client  2.6.4stable, latest 18-series server). This makes the whole extension completely useless.

**Comment by georgehrke** [comment]
This is the wrong repo. It has to be reported in the repository of the desktop client. If you search the issue tracker there, you will find an open issue.
