### ISSUE TITLE
Error on unlock

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#171]
After delete last file on directory E2ee and send an unlock return error 404

@er-vin @tobiasKaminsky who can test it ?

**Comment by georgehrke** [comment]
Did you delete the metadata before that?

**Comment by marinofaggiana** [comment]
I think, yes ... you close it ?

**Comment by marinofaggiana** [comment]
I have look my code, yes after DELETE metadata

**Comment by marinofaggiana** [comment]
ping here
