### ISSUE TITLE
Thank you for continuing to work on e2e Encryption!

### ISSUE THREAD

**Issue by sunjam** [nextcloud/end_to_end_encryption#172]
It is amazing to see this being developed with new [releases](https://github.com/nextcloud/end_to_end_encryption/releases).  Great work.

**Comment by skyrid3r698** [comment]
Has development stopped? It takes much longer for this app to be updated than every other app I use and I haven't seen any new features since almost a year. Although looking at the "Issues" there is a high demand for features/bug fixes..

**Comment by BirdInFire** [comment]
> Has development stopped? It takes much longer for this app to be updated than every other app I use and I haven't seen any new features since almost a year. Although looking at the "Issues" there is a high demand for features/bug fixes..

it's seem they totally have abandoned it, will stop recommend them and push other to seafile (for E2E) and other services to agenda etc.
it's a shame to see they continue to market E2E when E2E is totally un-usable and un-maintained

**Comment by CarlSchwan** [comment]
Development has not stopped
