### ISSUE TITLE
Can't sync with desktop sync client 2.6.5 with end_to_end_encryption enabled

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/end_to_end_encryption#177]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Enable E2E app in NC 19
2. Start desktop sync client 2.6.5, create a folder within the synced path and choose to encrypt it in the sync client. 
3. Put content into the newly created and encrypted folder.

### Expected behaviour
The encrypted folder is synced as regular folders

### Actual behaviour
The desktop sync client get stuck in the sync process not doing much,

### Server configuration

**Operating system:**
CentOS 6
**Web server:**
Nginx
**Database:**
MariaDB 10.1
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
19.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 17 to 19
**Where did you install Nextcloud from:**
Git and stable19 branch

**Comment by georgehrke** [comment]
See https://github.com/nextcloud/end_to_end_encryption/releases/tag/v1.5.2-beta1

Please update the e2e app and also update the clients.

**Comment by georgehrke** [comment]
https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590 contains a more complete guide
