### ISSUE TITLE
Metadata info

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#18]
@schiessle Hi,a question  where the metadata json is memorized from server side and the metadata is associate to directory name od directory fileID ?

**Comment by tobiasKaminsky** [comment]
@marinofaggiana is its in $dataFolder/data/appdata_$rarndomID/end_to_end_encryption/meta-data

For what to you need access to it?

**Comment by schiessle** [comment]
> its in $dataFolder/data/appdata_$rarndomID/end_to_end_encryption/meta-data

small fix, you missed the path to the e2e folder, the correct path is: `$dataFolder/data/appdata_$rarndomID/end_to_end_encryption/$pathOfTheE2eFolder/meta-data`
