### ISSUE TITLE
unable to upload files to e2ee folder on external HD with stable 3.13.0 app

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/end_to_end_encryption#186]
i just updated app to its latest version 1.5.2 and e2ee folders started to work fine with stable nextcloud 3.13.0 app except if i create e2ee folder on external HD via USB, shared via smb i protocol.  that case the nextcloud android app does not allow me to upload any files into it.  it gives me an error.  i think there are e2ee permissions problems if the e2ee folder is hosted on external HD?

![Screenshot_20200819-095530](https://user-images.githubusercontent.com/35575744/90607885-23ffcc80-e202-11ea-981a-a81ee116c34a.png)

**Comment by georgehrke** [comment]
@tigernero79 Can you please fill the issue template. We didn't just put it there for fun, but we actually need all the information to have a chance to reproduce it.

**Comment by tigernero79** [comment]
you are absolutely right I will calmly make a complete list.  at the moment, however, it is sufficient to create an encrypted folder on external drives mounted via the smb protocol to have the error of inability to load any file.  i have nextcloud 19.0.1, with e3e app updated to today 1.5.3, latest stable android app 13.3.0, php 7.3.x raspbian os system with lamp system

**Comment by tigernero79** [comment]
@georgehrke 

### Steps to reproduce
1. upload file on external e2ee folder
2. external folder then protocol smb
3. error upload only external folder e2ee then smb protocol

### Expected behaviour
I should be able to upload files to the e2ee folder located on external storage

### Actual behaviour
upload to external storage folder fails

### Server configuration

**Operating system:**

Raspbian OS (DEBIAN) or UBUNTU 20.04

**Web server:**
Server version: Apache/2.4.38 (Raspbian)
 
**Database:**
Ver 10.3.23-MariaDB-0+deb10u1 for debian-linux-gnueabihf on armv7l (Raspbian 10)

**PHP version:**

PHP Version 7.3.19-1~deb10u1

**Nextcloud version:** (see Nextcloud admin page)

19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
update to 19.0.0

**Where did you install Nextcloud from:**
da download file

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - announcementcenter: 3.8.1
  - apporder: 0.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - camerarawpreviews: 0.7.8
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - end_to_end_encryption: 1.5.2
  - external: 3.6.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_automatedtagging: 1.9.0
  - files_downloadactivity: 1.8.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.0.0
  - impersonate: 1.6.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - music: 0.16.0
  - news: 14.1.11
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.1
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sharepoint: 1.7.0
  - socialsharing_diaspora: 2.1.0
  - socialsharing_email: 2.1.0
  - socialsharing_facebook: 2.1.0
  - socialsharing_twitter: 2.1.0
  - spreed: 9.0.3
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:

If not, provide at least the version number of the End-to-End-Encryption app.
v.152
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "tigernero.duckdns.org",
            "tigernero.no-ip.org",
            "montesarchio.duckdns.org",
            "vallecaudina.duckdns.org",
            "klisdjeb2zf7i6jivhnhq6c4ckcyt6fyjxlndqxcx2kajmmpwpzemeyd.onion",
            "192.168.6.100",
            "*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "https:\/\/tigernero.duckdns.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "filelocking.enabled": true,
        "force_language": "it",
        "simpleSignUpLink.shown": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "twofactor_webauthn"
        ]
    }
}
or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
chrome 
**Operating system:**
windows 10
### Logs



#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"8lqnGi27si0mynQ56v7K","level":2,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"","user":"--","app":"OC\\Log\\Rotate","method":"","url":"--","message":"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PHP","method":"DELETE","url"${"reqId":"Xx8U9lZS2ZlORwci59kxEwAAAAk","level":3,"time":"2020-07-27T18:40:10+00:00","remoteAddr":"151.75.141.33","user":"Tiger","app":"PH
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tigernero79** [comment]
@georgehrke 

another thing if it can be used: even on e2e folders not mounted externally but located directly where installed nextcloud upload does not occur from an android application if you select upload files, while if from an android application if you upload a photo taken at the moment via the application it goes

**Comment by georgehrke** [comment]
And it works as expected when you don't use an external mount?

**Comment by tigernero79** [comment]
@georgehrke if i don't use external media i noticed that it works quite well only other bug from android application nextcloud if i choose upload file and take a png image file it gives me the same error unable to upload, if i choose to upload text file it goes instead.

**Comment by georgehrke** [comment]
@tobiasKaminsky Is uploading text using the direct editing API or how does that work?

**Comment by tigernero79** [comment]
always from android application instead if I choose to upload files from camera instead image is loaded correctly, so I assume that upload file option for e2ee folders has some problem with image format or at least with png format

**Comment by tigernero79** [comment]
@georgehrke 

point of the situation on e2ee folders located on external folders any file that cannot be uploaded.

on e2ee folders that are not mounted on external devices upload is fine except for png image files, jpg image files are loaded problem with png files?

second test:


took png photos from the pictures folder of my pixel 2 xl and moved to the root upload in the e2ee folder it worked.

so from what I understand. for e2ee folders everything works fine but for png files located in pictures folder it does not load.

on e2ee folders on external mount loading is successful with all files

**Comment by tigernero79** [comment]
@georgehrke correct translation to make you understand better

**Comment by tigernero79** [comment]
i am thinking after various tests that many of these problems come with android application, something is not interfacing well with your e2ee app.

**Comment by tigernero79** [comment]
@georgehrke this morning it seems to work sending on e2ee folders on external HD I do other tests, changes have been made that I don't know?

**Comment by georgehrke** [comment]
There has not been any release since Monday

**Comment by tigernero79** [comment]
@georgehrke seems to work on my 2 nextcloud installations, only problem error if I tend to create e2ee folder inside an already existing e2ee folder.  it gives me error unable to complete server unavailable operation.  mha ..

![Screenshot_20200820-093332](https://user-images.githubusercontent.com/35575744/90730367-4f4cef00-e2c8-11ea-96ed-6158e2c81a60.png)

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Is uploading text using the direct editing API or how does that work?

No, upload is always upload.
Only if you click on a md file, you can directly edit it (but not with e2ee)
