### ISSUE TITLE
Endpoint for thumbnails

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/end_to_end_encryption#19]
Implement new get/post so that a client can push an encrypted thumbnail so that an e2e client can download these to show thumbnails even for encrypted folders.

(as @rullzer said it is very easy and @schiessle wants to implement it)

**Comment by tobiasKaminsky** [comment]
@rullzer @schiessle do we want to implement this "soon", so this can be in next e2e milestone?

**Comment by rullzer** [comment]
define 'soon'...
