### ISSUE TITLE
incompatible End-to-End Encryption 1.0 on iOS 13.6.1 ?

### ISSUE THREAD

**Issue by PRhodan** [nextcloud/end_to_end_encryption#192]
Web Nextcloud 18.0.7
Web **End-to-End Encryption 1.4.0** activated
iOS 13.6.1 Nextcloud 3.0.5.8; **End-to-End Encryption 1.0**

Hello,
because I have been looking for a solution for several umpteen minutes without success:
I get the error message (End-to-End Encryption version incompatible) like in the picture.
For iOS I have the latest nextcloud version from the store.
What can I do there?
Greeting
![IMG_2643](https://user-images.githubusercontent.com/37460114/91312328-68680b00-e7b4-11ea-8987-5fa3e7dba7b5.PNG)

**Comment by georgehrke** [comment]
As it says in the error message. Please update the server!

Minimum required is Nextcloud 19 and E2E App 1.5.2

**Comment by PRhodan** [comment]
this is the first what i have done:
Nextcloud 18.0.7
Your version is current.

**Comment by georgehrke** [comment]
We will start rolling out the 19 release to all users soon.
You can always update to 19 manually

**Comment by PRhodan** [comment]
ok, many thanks
