### ISSUE TITLE
Windows <-> Linux sync problem

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/end_to_end_encryption#196]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Upload & sync encrypted file to the cloud (in my case 3 image files inside of a folder) using linux client
2. Make sure files are synced, they are visible when using android app
3. Back on Windows, files are not synced, they do not appear anywhere. whole folder missing

### Expected behaviour
Files should sync 
### Actual behaviour
Files uploaded via linux client are not syncing (?). Android <-> Windows works fine.
### Server configuration

**Operating system:** ubuntu 20 
latest E2EE app and NC 19.0.* snap

**Comment by georgehrke** [comment]
Can you please fill __the entire__ issue template and provide all requested logs?

**Comment by pilsnerbeer** [comment]
I must apologize - as soon as I posted this I realized the folder wasn't ticked in the client setting and thus was not syncing. I can see the folder  now.
