### ISSUE TITLE
end-2-end-encryption - Alpha State or ready for production use ?

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/end_to_end_encryption#198]
Dear All

just did the upgrade to NC 19.0.2.

End-to-End Encryption  is under the category "Featured" - means ready for production use.

But the Apps text tells -->

Provides the necessary endpoint to enable end-to-end encryption. 
End-to-end encryption is still in alpha state. Use only with test data, never in production!

So, what is true now - alpha or ready for production ?

**Comment by bcutter** [comment]
According to the big bang announcement... https://nextcloud.com/blog/production-ready-end-to-end-encryption-and-new-user-interface-arrive-with-nextcloud-desktop-client-3-0/ ...it should be "production ready".

But with all the bugs namely having huge performance issues and MySQL database going crazy and the fact nothing happens in that corner... I´d still vote for Alpha. Maybe Beta. Unfortunately.

Have a look at https://github.com/nextcloud/end_to_end_encryption/issues/191#issuecomment-683272921 e. g.

**Comment by Githopp192** [comment]
yes, cutter, this might be true .. it's also my feeling. But let's see about the official answer

**Comment by jospoortvliet** [comment]
The description of the app is simply outdated. Will be fixed in the next release.

**Comment by ho1ger** [comment]
Just a remark: why on earth do you label something production ready when it is not. What you have currently is beta software. And this should be communicated like this if you still expect that things go wrong on systems you cannot test on.
