### ISSUE TITLE
Overview: Initial development of the server part of end-to-end encryption

### ISSUE THREAD

**Issue by schiessle** [nextcloud/end_to_end_encryption#2]
- [x] Implement basic rest calls to
  - [x] store and get the users private key
  - [x] sign the public key and return it
  - [x] get users public key
  - [x] store, get and update meta data file
  - [x] mark folder as encrypted / unencrypted
  - [x] lock file during upload to avoid simultaneous uploads
- [x] propfind to detect encryption state
- [x] don't allow to download file while it is locked (sabredav plugin)
- [x] add capabilities to check whether client-side encryption is enabled or not.
- [x] filesystem wrapper to move delete / rename meta data files
- [x] block access to encrypted files in the web interface
- [x] hide file operations in Web interface and a nice icon for e2e folders (https://github.com/nextcloud/server/pull/6670)
- [x] unit tests (https://github.com/nextcloud/end_to_end_encryption/pull/1)

**Comment by MorrisJobke** [comment]
All items are done -> closing
