### ISSUE TITLE
Option to unlock folder as user as fallback

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/end_to_end_encryption#20]
- pre-write hook moves file to change to a $file.part (hidden) name to prevent overwriting it & stores meta-data
- if the lock does not get reverted for >=24h the user can see the lock in a new setting page and manually unlock it, with a warning
- if the folder lock is reverted the $file.part is reverted, the corresponding metadata is restored

**Comment by tacruc** [comment]
This would be a great opportunity. My crypt folder is locked now for 6 hours by a other client. The thing is that I only have one client right now. So I don't think that it is going to be unlocked.

**Comment by tobiasKaminsky** [comment]
As discussed this should happen automatically after 24h (calculated after last write on a chunk)
