### ISSUE TITLE
Disable/Restrict E2EE for specific user/group

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/end_to_end_encryption#202]
Nextcloud 19.0.3
End2End Module 1.5.2
Php 7.4

How it should been:
End 2 End Module should be able to be activated for specific users or groups

How it is (as far as I found, please tell me otherwise, if I didnt find it):
End 2 End Module activates automatically for every user.

Hi,

Is there any way to possibly disable this module and use it for only specific users (like I created an E2EE Group and every user that is in there can use the feature).

For example on a Laptop the Client got updated to version 3.x and also on another PC and it activated itself for these accounts, The Laptop got restored from an old backup and now the phrase is gone. Now the passphrase is gone and I have to do the manual workaround with database and such.

Not every user wants to use this feature and be bugged with writing down and copying another key to all his devices.

**Comment by brtptrs** [comment]
This would be a great feature. On our system we would like to enable E2EE only once a user has taken part in training to know the features, possibilities and limitations of the system.
This is important to eliminate unnecessary support requests.

**Comment by CarlSchwan** [comment]
Implemented in https://github.com/nextcloud/end_to_end_encryption/pull/320 :tada:
