### ISSUE TITLE
Allow users to re-generate 12 words from mobile and desktop clients.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/end_to_end_encryption#203]
[Submitted to desktop repo as 2451](https://github.com/nextcloud/desktop/issues/2451), but would apply to mobile clients as well.  Please allow users to re-generate their 12 words before enabling encryption.  Thanks for considering.

**Comment by tobiasKaminsky** [comment]
Can you explain a bit more why this is should be neeeded?
The 12 work mnemonic is generated always new displaying it for first time.

**Comment by sunjam** [comment]
I suppose I'm looking for a "Regenerate" button to click on-demand from
client apps.  Thanks for considering.

**Comment by tobiasKaminsky** [comment]
What is the idea behind this? I fail to find a reason for this.
If you do not like the generated words, click cancel and start encryption again, then you will get other 12 words…
