### ISSUE TITLE
are you aware of this bug for v20 and later?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/end_to_end_encryption#215]
https://github.com/nextcloud/desktop/issues/2612

in practice, by enabling the nextcloud plugin, it stops synchronizing the folders and remains in synchronization waiting. as soon as you deactivate the plugin everything goes back to normal.

are you aware of the problem?

**Comment by hdlineage** [comment]
https://github.com/nextcloud/desktop/issues/2593

**Comment by tobiasKaminsky** [comment]
Seems to be indeed a duplicate.
