### ISSUE TITLE
Mnemonic Passphrase Issues

### ISSUE THREAD

**Issue by mrguymiah** [nextcloud/end_to_end_encryption#219]
I setup my Nextcloud server. Setup a couple of users, notably the admin, and then went to apps. I downloaded E2E and my Desktop client is asking for a mnemonic. I see a button to reveal it in the desktop client, but it makes sense that it's not displaying if it's asking me to input it. I've been looking around in the settings on my server and not seeing it. While looking up where to find this information, the only thing I came across was a 2017 post indicating that keys would not be generated for existing users and that they had to be recreated after enabling E2E, including the admin account. Considering I just loaded 400GB of family photos into the server for backup, I'm reaching out here to see if this is still the case or if it's old information. If not, where can I find the Mnemonic on the server so that I can get my desktop client working correctly?

**Comment by eibex** [comment]
The mnemonic will be shown to you on the Desktop Client when you first set it up, it won't be shown on the server. You don't have to recreate an account, that information you found must be outdated.

**Comment by basti1982** [comment]
@mrguymiah: I'm experiencing the same issue. When I activate e2ee, existing users get an empty mnemonic. When I create a new user, the mnemonic is shown.

Nextcloud Client: 3.2.0 for Linux (AppImage)
Nextcloud Server: 20.0.5

I think it's the same issue that is discussed in the community forums here: https://help.nextcloud.com/t/e2e-encryption-mnemonic-field-is-empty/46131

**Comment by joshtrichards** [comment]
> I setup my Nextcloud server. Setup a couple of users, notably the admin, and then went to apps. I downloaded E2E and my Desktop client is asking for a mnemonic. I see a button to reveal it in the desktop client, but it makes sense that it's not displaying if it's asking me to input it. I've been looking around in the settings on my server and not seeing it.

This sounds like correct behavior. The mnemonic is never entered on the server. It's entirely handled by the client. You enter/generate the mnemonic on the first client you use with E2EE. Then you need to use (enter) that same mnemonic on all your other client devices.

If someone odd is occurring mnemonic prompting/setup, please open an issue in the respective client's repository.
