### ISSUE TITLE
Update `supportedUserAgents` to allow 3rd party clients to use E2E -

### ISSUE THREAD

**Issue by Gestas** [nextcloud/end_to_end_encryption#221]
**Is your feature request related to a problem? Please describe.**
Yes. I'm writing a headless Nextcloud client that supports E2E encryption. When I make an API call to get the user's private key -
`https://<server>/ocs/v2.php/apps/end_to_end_encryption/api/v1/private-key?format=json` 

I get an error, `Client <my user-agent> is not allowed to access end-to-end encrypted content`. This is the first call I've implemented, I'm guessing I'll see this error on every call to `*ocs/v2.php/apps/end_to_end_encryption/api/*`.

This check has been implemented in [UserAgentManager](https://github.com/nextcloud/end_to_end_encryption/blob/bf76ace1f6b853ecaf90ec8549012465410c9c95/lib/UserAgentManager.php). I understand why the check exists, it's a reasonable way to ensure a customer is running a supported client. Unfortunately as it's currently implemented it's unfriendly to 3rd party developers as it requires user agent spoofing. 

**Describe the solution you'd like**
1. Add a [regex to the `supportedUserAgents`](https://github.com/nextcloud/end_to_end_encryption/blob/bf76ace1f6b853ecaf90ec8549012465410c9c95/lib/UserAgentManager.php#L40) that supports a user-agent extra string that indicates support for  E2E encryption. Something like -
`"\/e2e/i"` would work.
2. Update [the documentation](https://github.com/nextcloud/end_to_end_encryption/blob/master/doc/api.md).

**Describe alternatives you've considered**
I'm currently spoofing the user-agent string. 

**Additional context**
If we can settle on a regex I'm happy to submit a pull request for the change.

**Comment by CarlSchwan** [comment]
Would adding a specific header or query parameter good enough for you?

**Comment by Gestas** [comment]
I’m flexible, as long as it eliminates the need to spoof user-agent string.

**Comment by szaimen** [comment]
Done with https://github.com/nextcloud/end_to_end_encryption/pull/300

**Comment by Gestas** [comment]
@CarlSchwan @szaimen Thank you very much!
