### ISSUE TITLE
Latest master plugin no longer allows disabling.

### ISSUE THREAD

**Issue by mannp** [nextcloud/end_to_end_encryption#23]
I have removed and reinstalled the E2EE plugin by cloning the master branch into my plugin folder of the server and the plugin is immediately enabled with no means of disabling?

I would previously enable to test and then disable... now it is always enabled, is that by design?

**Comment by tobiasKaminsky** [comment]
It should behave like any other plugin.
What NC version do you run? At some point the plugin changed to NC13 only.

**Comment by mannp** [comment]
I noticed on the page it only showed v13, so I will uninstall as am on 12.04
