### ISSUE TITLE
The at() matcher has been deprecated. It will be removed in PHPUnit 10.

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/end_to_end_encryption#233]
> 1) OCA\EndToEndEncryption\Tests\Unit\BackgroundJob\RollbackBackgroundJobTest::testRun with data set #0 ('no', false, -1, -1)
The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

There are a lot of such warnings

**Comment by CarlSchwan** [comment]
Fix is here: https://github.com/nextcloud/end_to_end_encryption/pull/319
