### ISSUE TITLE
Deleted files skip the trash bin when encryption is enabled

### ISSUE THREAD

**Issue by nunesgh** [nextcloud/end_to_end_encryption#244]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a Text file, e.g. `test.md`.
2. Write anything within the file.
3. Delete the file.
4. Check the trash bin.

### Expected behaviour
The deleted file should be in the trash bin.

### Actual behaviour
The file is not there. It was completely deleted from my server.

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install of Nextcloud 19.

**Where did you install Nextcloud from:** Website tarball.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - appointments: 1.7.7
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.1.0
  - encryption: 2.7.0
  - end_to_end_encryption: 1.5.2
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.1
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.0.4
  - guests: 1.5.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - news: 14.2.2
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - polls: 1.4.3
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.4
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.3
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - photos
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_language": "en",
        "default_locale": "en_AU",
        "defaultapp": "files",
        "skeletondirectory": "",
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto"
    }
}

```
</details>

**Are you using external storage, if yes which one:** WebDAV

**Are you using encryption:** Yes.

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Firefox 81.0

**Operating system:** Linux Mint 20

### Logs

I was monitoring all the requested logs while performing the tests. The web server and the Nextcloud logs were not updated. The browser log was reporting some deprecation, including: `moment`, `jQuery`, `registerTabView`, and `Legacy tabs`.

**Comment by kongomongo** [comment]
sorry but "Deleted files skip the trash bin when encryption is enabled", isn't that by design?

```
List of activated apps:
App list
end_to_end_encryption: 1.5.2

```

https://nextcloud.com/endtoend/
Accepted feature loss
...
Server-side trash bin

**Comment by Mastertomspirit** [comment]
Yeah, it seems so.. Without E2E the trashbin app works fine.. 👍

**Comment by joshtrichards** [comment]
If a file is in a folder that is client-side encrypted (E2EE) than it bypasses the trashbin:

https://github.com/nextcloud/end_to_end_encryption/blob/7135af69a4a44be5f90ddeeba7ea20fd90893dbc/lib/AppInfo/Application.php#L92-L100

That's by design from all indications.

Part of the confusion I see in this thread may have arisen because both server-side and client-side encryption was enabled at the onset. That's [not supported](https://github.com/nextcloud/end_to_end_encryption#limitation). Part of the reason I believe is that they both use the `encrypted` column to indicate a file is encrypted.

https://github.com/nextcloud/server/blob/9de8e8e2244cfbed63f9c4d4b8abdd6092fa848c/lib/private/Files/Cache/CacheEntry.php#L112-L114

https://github.com/nextcloud/end_to_end_encryption/blob/7135af69a4a44be5f90ddeeba7ea20fd90893dbc/lib/EncryptionManager.php#L68-L72

The net result is - I suspect - that if both server-side and client-side modes are enabled, the listener for `moveToTrash` (that is created by the the `end_to_end_encryption` app) will match *every* file on the server - even those *just* server-side encrypted. 

This isn't a bug per se. It's documented that both forms of encryption should not be used together. This is just one of the side effects of ignoring that. :-)
