### ISSUE TITLE
Add compatibility for Nextcloud 22

### ISSUE THREAD

**Issue by MRFU510N88** [nextcloud/end_to_end_encryption#245]
As per the title, there is currently no app support for NC22.

**Comment by sunjam** [comment]
https://github.com/nextcloud/end_to_end_encryption/pull/242

**Comment by AlfredSK** [comment]
Nextcloud 22 was released on July 6, 2021. But still, no compatible end-to-end encryption app available on apps.nextcloud.com.

**Comment by bcutter** [comment]
> 
> 
> Nextcloud 22 was released on July 6, 2021. But still, no compatible end-to-end encryption app available on apps.nextcloud.com.

Only a matter of hours I hope as it seems like there´s activity in https://github.com/nextcloud/end_to_end_encryption/pull/242.

3 months up to now that´s a lot of time... 😞

**Comment by sunjam** [comment]
A solution to this is in implementing #8 and allowing users to manually
exchange keys between clients.  Removing the need for the server app will
end this continuous bout of catch up.

If e2e were to be become a dedicated client app it could even enjoy
popularity on other platforms such as Google Drive, Dropbox, etc.

**Comment by caleidon** [comment]
@rullzer Could you bump the version now that [242](https://github.com/nextcloud/end_to_end_encryption/pull/242) has been merged?
