### ISSUE TITLE
Add E2EE into Nextcloud, Not as an app

### ISSUE THREAD

**Issue by trymeouteh** [nextcloud/end_to_end_encryption#246]
E2EE is the best way to have your files stored on a cloud when it comes to security and privacy. Please have this feature integrated and maintained into Nextcloud itself and not as an app which can be clunky over time.

**Comment by tobiasKaminsky** [comment]
Lots of our "core" functions, e.g. calendar, contacts, talk are apps.
This is our concept, to have it modular and admins/user can enable/use only those what they need.

I do not see any real advantage to put it directly into server.

@skjnldsv
