### ISSUE TITLE
Block older clients

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/end_to_end_encryption#25]
Older clients (e.g. android <2.1) should be blocked when entering an encrypted folder, otherwise they could  delete files...

**Comment by tobiasKaminsky** [comment]
For android we need to change the useragent: https://github.com/nextcloud/android/issues/1852
But then we could block all ownCloud clients and all Nexcloud <2.1 for E2E.

**Comment by rullzer** [comment]
I'm not sure we have to infrastructure around to fix this. But I do agree. However I would just block them in general if E2E is enabled.

**Comment by tobiasKaminsky** [comment]
Currently we use the same useragent "Mozilla/5.0 (Android) ownCloud-android/$versionNumber".
As ownCloud is on version 2.5 and we will release 2.1 we cannot block them that easily depending only on the versionNumber. So we need to change the user agent...

**Comment by tobiasKaminsky** [comment]
@rullzer what is missing on server side to do this?

**Comment by marinofaggiana** [comment]
I use : Mozilla/5.0 (iOS) Nextcloud-iOS/2.19.0 

e.g. < 2.19.0

**Comment by georgehrke** [comment]
@camilasan @misch7 What version of the desktop client should we block?

**Comment by georgehrke** [comment]
> @rullzer what is missing on server side to do this?

Not much, we can just listen on Sabre/DAV requests in check the user agent, no big deal.
Would should the error message be like?

**Comment by georgehrke** [comment]
it seems this was already worked on: https://github.com/nextcloud/end_to_end_encryption/blob/9e71e2d282ccd106cbe3f5f62ad60abd5d05d072/lib/UserAgentManager.php
