### ISSUE TITLE
     E2EE is currently not compatible to be used together with server-side encryption

### ISSUE THREAD

**Issue by JimLoose** [nextcloud/end_to_end_encryption#274]
https://github.com/nextcloud/end_to_end_encryption/blob/master/README.md
> E2EE is currently not compatible to be used together with server-side encryption

is this still an issue? E2EE works flawless with with server-side encryption enabled on my NC22

**Comment by JoshuaPettus** [comment]
I believe they are talking about the full "serverside encryption" nextcloud plugin.    Nothing to do with whatever hard drive encryption you place outside of nextcloud.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/end_to_end_encryption/pull/231#issuecomment-828308637
