### ISSUE TITLE
Support Nextcloud 24

### ISSUE THREAD

**Issue by bcutter** [nextcloud/end_to_end_encryption#296]
Same like
- https://github.com/nextcloud/end_to_end_encryption/issues/245 for NC v22 and
- https://github.com/nextcloud/end_to_end_encryption/issues/273 for NC v23

Nothing more to add. Will likely try my luck with https://github.com/nextcloud/end_to_end_encryption/issues/273#issuecomment-1072152722 again, but NC 24 comes with some changes (like PHP 8.1 support) so E2EE should be intensively tested to avoid breaking things.

**Comment by CarlSchwan** [comment]
Version 1.10.0 is now available https://apps.nextcloud.com/apps/end_to_end_encryption
