### ISSUE TITLE
CardDAV and CalDAV stop working with E2EE enabled.

### ISSUE THREAD

**Issue by mannp** [nextcloud/end_to_end_encryption#3]
Both are working fine before enabling the plugin and both work fine again once E2EE is disabled again.

There is no mention of this being a restriction, so have assumed it is a bug.

**Comment by schiessle** [comment]
Thanks, this is probably caused by the sabredav plugins implemented here. I will look into it.

**Comment by schiessle** [comment]
@mannp this should solve the issue: https://github.com/nextcloud/end_to_end_encryption/pull/4 Maybe you can give it a try and report back? Thanks a lot!

**Comment by mannp** [comment]
@schiessle thanks for the update.

I am using a git version of the plugin and have done a new git pull for your changes, but sill lose access with E2EE enabled.

Am I picking up all the changes? Are they solely in an updated plugin?

I have done the git pull and rebooted my server just in case and still have no access via CardDav or Caldav; getting 404.

I also lose connection on my android phone through davdroid.

**Comment by schiessle** [comment]
@mannp you need to checkout the branch with the fix: `git checkout only-files`

**Comment by mannp** [comment]
@schiessle Oops! So, with initial tests on that branch I am able to sync both Dav's on the mac and android devices.

I will take a further look tomorrow, as I haven't configured e2ee yet, but initial tests look good 👍

**Comment by schiessle** [comment]
Great, thanks for testing @mannp !

**Comment by mannp** [comment]
@schiessle Hi there. So I have had no issues with CalDAV and CardDav syncing now, but I now cannot upload files from the latest android app to my server, they just error out.

I also cannot setup E2EE which might be related to not being able to upload files.

Happy to create a new issue if these are unrelated to CardDav and CalDAV.

The errors in my log are as follows;

> end_to_end_encryption | Can't create public key: could not sign the CSR, please make sure to submit a valid CSR
-- | --

> PHP | openssl_csr_sign(): cannot get CSR from parameter 1 at /config/www/nextcloud/apps/end_to_end_encryption/lib/SignatureHandler.php#60
-- | --


> webdav | OCA\DAV\Connector\Sabre\Exception\InvalidPath: Dot files are not allowed
-- | --

**Comment by schiessle** [comment]
At first sight I would say that this is not related, creating a public key should be completely independent from the DAV request. Looks like the Android client sends a wrong CSR... @tobiasKaminsky what do you think?

**Comment by schiessle** [comment]
@mannp just to double check, if you switch back to the master branch it works again?

**Comment by tobiasKaminsky** [comment]
@schiessle the first error message is related to E2E, but the third one "InvalidPath: Dot files are not allowed"....?

**Comment by schiessle** [comment]
@tobiasKaminsky maybe you can try the pull request as well? https://github.com/nextcloud/end_to_end_encryption/pull/4? Then we can debug it together...Thanks!

**Comment by mannp** [comment]
@schiessle Thats a good question as I hadn't bothered to setup E2EE before as I didn't want to sacrifice the DAV's to test it.

I will revert back to master and try to setup directly, but it would be good if @tobiasKaminsky has chance to test too, as the interoperability is pretty critical 👍  and perhaps not best left to my level of testing :)

**Comment by tobiasKaminsky** [comment]
@schiessle I have the same problem, but also with your PR :/

**Comment by ConorIA** [comment]
I can confirm that my Android app hangs at "Generating new keys..." when the #4 branch is active on the server.

**Comment by mannp** [comment]
It's not particularly clear to me but it seems the csr error is present in both branches.

**Comment by mannp** [comment]
Did this one get resolved? or is in progress, or not being looked at :) ?

Thanks in advance

**Comment by schiessle** [comment]
@mannp we could just test it successfully with some small changes. I merged it now into master. Please reopen the issue (or create a new one) if you still experience any problem.
