### ISSUE TITLE
Max dimension Upload

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#31]
Hi boys, exists in your client a limit of dimension for file ? I thought 500 MB (for single file) ... ?

@rullzer @tcanabrava @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
On Android there is no limit set by us. Maybe there is a limit by Android itself. 
We use chunked upload, so if an upload is failing after 300/350mb it will get resumed at 299 as we use 1mb chunks.

**Comment by marinofaggiana** [comment]
ah ... emm no I don't have a issue for Upload file but my problem is for read/write data from to disk for encrypted file and for openSSL, so I thought 500 MB (for single file) max ...

**Comment by rullzer** [comment]
No limit here. Well we have to store the encrypted file before upload. So the limit is basically the amount of tmp space.

**Comment by schiessle** [comment]
I agree with @rullzer we shouldn't define a arbitrarily limit. Limits might come from the device you use, but that's not our decisions.
