### ISSUE TITLE
Reset end-to-end encryption disabled even if user has created an encrypted folder

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/end_to_end_encryption#355]
1. Install the app
2. Create a connection with the Desktop Client with a user
3. Create a folder and encrypt it
4. From the web ui, reset end-to-end encryption
5. Repeat step 3
6. Restart the Desktop Client
7. From the web ui, try to reset end-to-end encryption

This is not possible as the button remains greyed out.

System Report: [2022-10-26.md](https://github.com/nextcloud/end_to_end_encryption/files/9870447/2022-10-26.md)

**Comment by joshtrichards** [comment]
I'm a bit confused about what version of the app you were using. Your system report says v1.10.0, but that was for NC24. Looks like you force enabled it with NC25 per your config. But the more confusing part is that v1.10.0 didn't have the "Reset" option in it.

That came in v1.11.0 via #305.

**Comment by pmarini-nc** [comment]
Maybe it was an error on my side. Just tested with server 28.0.1 and end_to_end_encryption 1.14.1 and it works as expected.

I think this can be closed.
