### ISSUE TITLE
Support Nextcloud 25

### ISSUE THREAD

**Issue by bcutter** [nextcloud/end_to_end_encryption#357]
Please make E2EE app compatible for Nextcloud version 25.

Like with
- https://github.com/nextcloud/end_to_end_encryption/issues/245
- https://github.com/nextcloud/end_to_end_encryption/issues/273
- https://github.com/nextcloud/end_to_end_encryption/issues/296

Starts to be a never ending story with this app always being one of the last.

To everyone tired of waiting for this app to support a new NC major release: you could try https://github.com/nextcloud/end_to_end_encryption/issues/273#issuecomment-1072152722 which always worked for me up to now.

**Comment by eibex** [comment]
Might be an issue to 1.10.1 being released but the app store server not receiving the update properly?

https://github.com/nextcloud-releases/end_to_end_encryption/releases/tag/v1.10.1

**Comment by MSe1969** [comment]
Some information:
I have a test instance on 25.0.1 and did some testing:

1. Installed the 1.11.0-beta.1, which is supposed to work on 25 => fail, not usable at all. When you paste several files into the encrypted folder on one device, it only partly syncs as encrypted and causes on the 2nd device a flood of sync errors. So I uninstalled it again.
2. Manually extracted the 1.10.1 tag from here: https://github.com/nextcloud-releases/end_to_end_encryption/releases/download/v1.10.1/end_to_end_encryption-v1.10.1.tar.gz, edited info.xml, fixed the tag info and declared compatibility with 25 => seems to work, will do further tests, before I upgrade my 'productive' instance. But looks promising so far. 
As before: A work-around option for people having (ssh) access to the server and write access to the nextcloud instance

**Comment by MSe1969** [comment]
@bcutter 
My 1st test was starting to use E2E on a 25 NC, which was promising.
Now I tested an upgrade of an existing E2E setup on a 24.0.7 NC - NOK/issues - will have to "fine-tune" the upgrade approach and report back...

**Comment by MSe1969** [comment]
UPDATE:
OK, works - keep it simple (my first try was unnecessarily complicated):
If you have 24.0.7 with E2E running, just do the following:
- Upgrade normally to 25.0.1
- Edit appinfo/info.xml og the E2E app accordingly
- php occ app:enable end_to_end_encryption

That's it.

**Comment by sergeng** [comment]
> UPDATE: OK, works - keep it simple (my first try was unnecessarily complicated): If you have 24.0.7 with E2E running, just do the following:
> 
>     * Upgrade normally to 25.0.1
> 
>     * Edit appinfo/info.xml og the E2E app accordingly
> 
>     * php occ app:enable end_to_end_encryption
> 
> 
> That's it.

you mean changing bumping E2E compatibility to NC25 in appinfo/info.xml without upgrading the E2E release?

**Comment by MSe1969** [comment]
When I did the test - see above - and simply edited the e2e app-info of the app suitable for NC24 and all worked perfectly fine. Now, the NC25 compatible version has issues! And I can't downgrade, as in that case, NC insists on upgrading.

**Comment by eibex** [comment]
I'm experiencing no issues on 1.11.0

**Comment by MSe1969** [comment]
I have 1.11.1, which is what is being updated, and what you are forced to use - that one is in fact the one coming from the non-working beta.

Normally, files are uploaded in an encrypted state and on the server, you only see the file name being a hash and it is synced and decrypted to the other client(s).

When I did my tests using the 1.10.x version for NC24 with an edited info.xml, all worked perfectly fine, but once the 1.11.1 came out, it stopped working. 

In the case of 1.11.1, any new file is uploaded unencrypted and appears on the server with its original file name. On the other client(s), an error message appears stating that the file could not be synced/decrypted.
That by the way was the behavior, I had observed in my above testing already with the 1.11.0-beta.1

I assume the app has been tested officially, so there must be a specific condition causing this misbehavior.
Nevertheless, if I could meanwhile downgrade to the previously working app, I would be glad.
Thanks for any hint.

**Comment by MSe1969** [comment]
OK, I would love to work with 1.11.0, if that is working properly, however - 1.11.1 is what is being updated and also instelld, if you install E2E newly in NC25. I'll open an issue then

**Comment by eibex** [comment]
> Well the latest stable release is 1.11.0.
> 
> If you are using a beta version, please instantly report this issue (create new issue) as this indeed sounds quite serious.

The latest stable release is 1.11.1 on NC25

**Comment by MSe1969** [comment]
Look here: https://apps.nextcloud.com/apps/end_to_end_encryption
This is what the Nextcloud server seems to take to install the apps, and 1.11.1 is as well shown in the app list.
As mentioned - if you tell me, how to downgrade to 1.11.0, I will be very happy to use this version if that works.

**Comment by MSe1969** [comment]
Issue is 374 - regarding Nextcloud log - no entries related to this - would you like me to run with a certain log level or do something here to better support? Specific command?
