### ISSUE TITLE
12.0.4 to 13rc4, cannot re-enable plugin; oc_e2e_encryption_lock exists.

### ISSUE THREAD

**Issue by mannp** [nextcloud/end_to_end_encryption#37]
After upgrading to 13rc4 I re cloned the latest E2EE code from github and tried to re-enable the plugin.

The error results, although I am not able to find the table myself, as it doesn't seem to exist?

> An exception occurred while executing 'CREATE TABLE `oc_e2e_encryption_lock` (`id` INT NOT NULL COMMENT 'file id of the locked folder', `timestamp` INT NOT NULL, `token` VARCHAR(256) NOT NULL COMMENT 'token used to identify the client', UNIQUE INDEX id (`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1813 Tablespace for table '`nextcloud`.`oc_e2e_encryption_lock`' exists. Please DISCARD the tablespace before IMPORT.

**Comment by mannp** [comment]
Any one help me with this one please?

Thanks in advance

**Comment by mannp** [comment]
Anyone offer any help on this one please?

**Comment by tobiasKaminsky** [comment]
@schiessle maybe?

**Comment by schiessle** [comment]
@mannp if I remember correctly from another issue you meanwhile setup a new system so this is no longer a problem. I think the planed enhancements like unlocking files in the admin interface and resetting encryption keys will make this issue void. Feel free to re-open it if you think there is still something to do.

**Comment by mannp** [comment]
Ok @schiessle I am ok with closing it, but would welcome the unlocking files in admin functionaility as after swapping to redis, I am still not enjoying locking file issues.

When is that due to fall? 13.01? :)
