### ISSUE TITLE
some file types are not encrypted (png)

### ISSUE THREAD

**Issue by mtissington** [nextcloud/end_to_end_encryption#386]
### Steps to reproduce
1. E2E version 1.11.1
2. MacOS Client 3.6.6
3. Create Encrypted folder
4. Copy pdf to folder 
5. Copy png to folder
6. Navigate to user data folder on server
7. pdf is encrypted, png is NOT encrypted

### Expected behaviour
File should be encrypted

### Actual behaviour
File is not encrypted

### Server configuration

**Operating system:**
Debian 11

**Web server:**
Apache 
**Database:**

**PHP version:**
PHP 8.1

**Nextcloud version:** (see Nextcloud admin page)
25.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`No errors have been found``

**List of activated apps:**
<summary>App list</summary>

```
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - camerarawpreviews: 0.8.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - dav: 1.24.0
  - end_to_end_encryption: 1.11.1
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - imageconverter: 1.3.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 0.2.4
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - unroundedcorners: 1.0.8
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - circles: 25.0.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - encryption
  - photos: 2.0.0
  - suspicious_login
  - systemtags: 1.15.0
  - user_ldap
  - weather_status: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.oaklodge.build"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "https:\/\/cloud.oaklodge.build\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 1,
        "default_phone_region": "US",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "enable_previews": true,
        "preview_max_x": 1000,
        "preview_max_y": 1000,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\PNG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\TIF",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\DNG"
        ],
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes E2E

**Are you using an external user-backend, if yes which one:** no

### Client configuration
Firefox
**Operating system:**
MacOS

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Contains private file names
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Not relevent
```
</details>

**Comment by meonkeys** [comment]
dup of #382, although this is on macos instead of linux

**Comment by joshtrichards** [comment]
Duplicate of #382 

For future reference:

- See https://github.com/nextcloud/end_to_end_encryption/issues/382#issuecomment-1630343120
- https://github.com/nextcloud/end_to_end_encryption/blob/master/SECURITY.md#reporting-a-vulnerability

I'll also note that it's a near certainty this would have been a client matter not an issue with the E2EE server app (this repository). I say this because the server app doesn't handle unencrypted data at all. The client is the only party that can send unencrypted data.

From #382 it sounds like the behavior wasn't reproducible in the desktop client somewhere between v3.6.6 and v3.7.3.

They post their release notes here:

https://github.com/nextcloud/desktop/releases

But if you can reproduce it, please report through proper channels noted above not here. Thanks!
