### ISSUE TITLE
Decrypt E2E

### ISSUE THREAD

**Issue by Viceman256** [nextcloud/end_to_end_encryption#388]
I have an encrypted folder that is stuck, it won't sync in any desktop client. The other encrypted folder works fine, but I suspect the large size of this folder is causing issues. It was encrypted with E2E and working fine for a year or two. I'm now migrating this instance to a new server, with better control. 

My question is, can I decrypt the E2E encryption somehow, so I can download this data from the web instead?

**Comment by WuShufei** [comment]
E2e is disabled for the web client for security reasons, as the info page inthe NC website says.  But I also have had the problem described with a “stuck” file.  It is not marked as e2e locked, but upon moving it, it is no longer editable nor deleteable.

**Comment by Viceman256** [comment]
> E2e is disabled for the web client for security reasons, as the info page inthe NC website says. But I also have had the problem described with a “stuck” file. It is not marked as e2e locked, but upon moving it, it is no longer editable nor deleteable.

I am specifically asking about decrypting the files, so they become web accessible. Not accessing them on the web with E2E encryption enabled.

Moving the files is out of the question, as there's no way to access them. They are stuck as in the client will not download this folder.

**Comment by yahesh** [comment]
@Viceman256 As of today the [encryption-recovery-tools](https://github.com/nextcloud/encryption-recovery-tools) support the end-to-end encryption.

**Comment by joshtrichards** [comment]
@Viceman256 You would take the contents of your server's `datadirectory` (or external storage if using it). Then use the aforementioned offline recovery tools. Specifically these are the instructions:

https://github.com/nextcloud/encryption-recovery-tools/blob/master/end-to-end-encryption/README.md

> I am specifically asking about decrypting the files, so they become web accessible. Not accessing them on the web with E2E encryption enabled.

Using the approach above would accomplish this, but you'd certainly need admin access to your server (or cooperation from someone with admin access to provide the raw albeit encrypted data). It's not a web based activity.
