### ISSUE TITLE
Auto upload from Android app fails if e2e app is enabled

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/end_to_end_encryption#39]
The auto upload of images is failing if the folder doesn't exist. I'm not sure if that is more an android issue or an issue with the e2e encryption app, but since it works without the app being enabled, I open the issue here.

NC version: 13 beta4
End-to-End Encryption version: 1.0.1
Android app version: 2.0.0

Auto upload is configured to use subfolders for year/month. 

@nextcloud/android Can you have a look as well?

## Server error log
```
	Sabre\DAV\Exception\NotFound: File with name SofortUpload/Camera/2018 could not be located

    /var/www/nextcloud/apps-extra/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 168: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('SofortUpload/Ca...')
    /var/www/nextcloud/apps-extra/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 109: OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->getNodeForPath('SofortUpload/Ca...')
    [internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 164: require_once('/var/www/nextcl...')
    {main}
```

**Comment by tobiasKaminsky** [comment]
Well..we (on android) create the folders if they do not exist.
But only on upload and locking is done before and this fails as the folder does not exist...

So the subfolders needs to be created before uploading and also being checked if they are / need to be encrypted...

**Comment by mario** [comment]
@tobiasKaminsky maybe create the structure on start of upload?

**Comment by tobiasKaminsky** [comment]
We do not create them at all, but rely on webdav for doing this.
But yeah, I fear that we now have to do it by hand.

@schiessle am I allowed to create these folders without a lock? I suspect not to, or? So I would first have to find the encrypted root folder and then lock it, create the subfolders and then unlock? :S

**Comment by marinofaggiana** [comment]
it should be automatic on the server side for a subfolder of encrypted folder

**Comment by tobiasKaminsky** [comment]
As discussed with @schiessle, this is the way I am doing it now on android:
on entering a folder I check if this folder is a subfolder of any encrypted folder. So only the topmost folder needs to be set as encrypted and the whole tree beneath it is automatically encrypted.

**Comment by tobiasKaminsky** [comment]
This should be now fixed with latest commit: https://github.com/nextcloud/android/pull/1944/commits/e335056edf25931364a36b76c7761ca860c216bc

We will release a RC1 soon. If it happens again, please create a new issue on android github.

**Comment by marinofaggiana** [comment]
When is available ? (server side E2E) ?

**Comment by marinofaggiana** [comment]
automatically ? client side ?
