### ISSUE TITLE
MkCol on subfolder returns 404 instead of 409

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/end_to_end_encryption#40]
When trying to create a subfolder on a parent that does not yet exist, mkcol suppose to send 409 (ref: https://tools.ietf.org/html/rfc4918#section-9.3). With this we then can recursivly go up and create the folders. 
But with this app enabled we get 404 back, which is wrong:
https://github.com/nextcloud/end_to_end_encryption/blob/master/lib/Connector/Sabre/LockPlugin.php#L168

@schiessle 

Related to #39

**Comment by rullzer** [comment]
As mentioned this breaks the webdav RFC.

Also it breaks it on the whole instance not just in the E2E folders ;)
