### ISSUE TITLE
I think I have corrupted encrypted files since an update

### ISSUE THREAD

**Issue by ffs69** [nextcloud/end_to_end_encryption#411]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Activate E2E Encryption
2. Many files and especially .jpg and .txt are corrupted and unreadable

### Expected behaviour
Open and download files normally.

### Actual behaviour
Many files and especially .jpg and .txt are corrupted and unreadable. Via the web interface the .jpg files display: Error loading. And the .txt files display: HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:encoding:binary:HEND.

In the logs file I have :
Error: imagecreatefromstring(): Data is not in a recognized format at /var/www/vhosts/xxxxxxx/httpdocs/lib/private/legacy/OC_Image.php#758

### Server configuration

**Operating system: Debian**

**Web server: Apache**

**Database: MariaDB**

**PHP version: 8.1**

**Nextcloud version: 25.0.5** (see Nextcloud admin page)

**Updated from an older Nextcloud**

---

Hi,

Many of my .jpg and .txt files have become corrupted. And unfortunately I don't have a recent backup.

It seems that the same kind of problem has already occurred in the past:
https://github.com/nextcloud/server/issues/3958
https://github.com/nextcloud/server/issues/8311

Is there a working solution since? I'm surprised the problem is still happening.

Many thanks in advance, I am very very bad!

C.

**Comment by yahesh** [comment]
The header `HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:encoding:binary:HEND` hints at that this is **not** related to the end-to-end encryption but to the server-side encryption.

**Comment by ffs69** [comment]
It was a mistake on my part, I misidentified and miscategorized my problem, sorry and thank you very much for the correction.
