### ISSUE TITLE
Feedback at web backend for encrypted folders

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/end_to_end_encryption#43]
Hi,

would be great, if an user get a feedback when he / she clicks on an encrypted folder at nextcloud web backend. Could you please add any message?

At the chrome console there is a 403 error message, which should not appear:
```
Failed to load resource: the server responded with a status of 403 ()
client.js?v=a969e03c-0:421 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagNameNS' of null
    at Client._getSabreException (client.js?v=a969e03c-0:421)
    at client.js?v=a969e03c-0:485
    at <anonymous>
```

Regards,

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/35030842-dc8ba8c2-fb60-11e7-885f-7ed02378713f.png)

For me, with app master, I get a warning.

@schiessle is the newest app version released?

**Comment by schiessle** [comment]
@tobiasKaminsky I think this should already be there in the previous release. But I just released a v1.0.2, this was on my todo anyway... Maybe you can also give it a try? Thanks!

**Comment by tobiasKaminsky** [comment]
Yes, still works for me, although it is 1.0.2 and not 1.0.3...

**Comment by benhartwich** [comment]
I´ve upgraded to 1.0.2 recently, but I can´t see the info message like you´ve shown at the screenshot. I´m using Nextcloud 13 RC1 on Debian 9.

**Comment by tobiasKaminsky** [comment]
What do you see when clicking on it? Nothing?
Do you see the lock symbol for encrypted folders?

**Comment by tobiasKaminsky** [comment]
@schiessle entering an encrypted folder should not be possible?

**Comment by schiessle** [comment]
don't know how this is possible. I can't reproduce it. The app is enabled, right? Do you see any error messages in the nextcloud.log?

**Comment by benhartwich** [comment]
Of course, the app is enabled. 

Nextcloud.log says:
`{"reqId":"DbBWyJOjhEKDbXJtbnnI","level":4,"time":"2018-01-19T12:25:03+00:00","remoteAddr":"","user":"","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Encrypted","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client not allowed to access end-to-end encrypted content\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/kunden\\\/nextcloud-beta\\\/httpdocs\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php(124): OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkUserAgent('Mozilla\\\/5.0 (Wi...', '\\\/Encrypted')\\n#1 [internal function]: OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/kunden\\\/nextcloud-beta\\\/httpdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/kunden\\\/nextcloud-beta\\\/httpdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/kunden\\\/nextcloud-beta\\\/httpdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/kunden\\\/nextcloud-beta\\\/httpdocs\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/kunden\\\/nextcloud-beta\\\/httpdocs\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/kunden\\\/nex...')\\n#7 {main}\",\"File\":\"\\\/var\\\/kunden\\\/nextcloud-beta\\\/httpdocs\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":169}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.11"}`

**Comment by vibora** [comment]
Same thing is happening over here:
remoteAddr":"","user":"","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Encrypted","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client not allowed to access end-to-end encrypted content\"

Used clients: Windows and iOS

**Comment by benhartwich** [comment]
@schiessle I´m testing it on my beta nextcloud 13.0 and I can access this folder shortly, then it jumps back to main view with the label "this operation is not allowed". Web console says:
`core.js?v=318406ba-0:5729 PROPFIND https://beta.speibox.de/remote.php/webdav/Encrypted 403 ()`

If this should be the default behaviour then this topic seems to be solved.

**Comment by tobiasKaminsky** [comment]
Yes, this is the right feedback, as you can see in second post.

**Comment by lenusch** [comment]
I have several Errors with Federation Share (same NC) and Encryption turned on. 
Files larger than 10MB wont be uploaded anymore, i have max upload .... Settings all to 8G
