### ISSUE TITLE
Implement headers X-NC-E2EE-SIGNATURE and X-NC-E2EE-COUNTER

### ISSUE THREAD

**Issue by allexzander** [nextcloud/end_to_end_encryption#437]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We need new headers supported on the server as per https://github.com/nextcloud/end_to_end_encryption_rfc/blob/v2.1/RFC.md (see **#modifying-and-accessing-content-of-an-end-to-end-encrypted-folder** and **#uploading-payload-and-metadata-file-step-5--8**).

**Describe alternatives you've considered**

**Additional context**

**Comment by allexzander** [comment]
@tobiasKaminsky As discussed, created this issue

**Comment by artonge** [comment]
@tobiasKaminsky I would like to make sure that I fully understand the RFC, especially the checks that the server must perform.

Regarding `X-NC-E2EE-COUNTER`:

- The client bumps the counter in the metadata locally,
- The client `POST /lock/<folder-id>` with the bumped counter in the header,
- The server check that the bumped counter in the header is greater than the one in the server's metadata:
    - If `true`, accept request,
    - If `false`, reject request.

Regarding `X-NC-E2EE-SIGNATURE`:

- The client forges the new metadata,
- The client `PUT /meta-data/<folder-id>` with the signature in the header,
- The server checks that the signature in the header is the same as the one in the request body:
    - If `true`, accept request,
    - If `false`, reject request.

Is that it?

**Comment by tobiasKaminsky** [comment]
Can you check the signature? I am unsure if server can do this.

**Comment by AndyScherzinger** [comment]
Please also ensure these headers are reflected in the API docs

**Comment by tobiasKaminsky** [comment]
> Regarding `X-NC-E2EE-SIGNATURE`:
> 
>     * The client forges the new metadata,
> 
>     * The client `PUT /meta-data/<folder-id>` with the signature in the header,
> 
>     * The server checks that the signature in the header is the same as the one in the request body:
>       
>       * If `true`, accept request,
>       * If `false`, reject request.
> 
> 
> Is that it?

As a starting point, please let server do this:
- store signature alongside with metadata when receiving
- no check (I doubt that this is possible at all on server, and it is not useful, as sever is always assumed as "hacked".
- send signature back as header when querying metadata, so that clients can check it

**Comment by artonge** [comment]
Both headers have been implemented in https://github.com/nextcloud/end_to_end_encryption/pull/405
