### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#45]
On "Activity" API view the file name identifier of encrypted file ..
![schermata 2018-01-23 alle 17 19 12](https://user-images.githubusercontent.com/8616947/35286991-b3204fbe-0061-11e8-91e4-c7e9e433e0f0.png)

This is not a good information.

**Comment by tobiasKaminsky** [comment]
@nickvergessen as the master of activities ;-)
The question is what to display instead? Maybe just some "encrypted File" placeholder?

**Comment by nickvergessen** [comment]
Well there is no flag on the file for the activity app to detect this...

Also note that the activity app is bound to core atm, so mostlikely we can only fix it for 13.0.1

**Comment by tobiasKaminsky** [comment]
Ah right...We only have a flag for the top encrypted folder.
On client we just go up until either root or encrypted folder flag.
But this might be a bit heavy to do this on each file which is shown on activity app...

**Comment by nickvergessen** [comment]
I just realised, that on the server we have no way to recover the real-file path.
So things left would be: if name is `[0-9a-f]{32}` we try to find out if one of the parent folders is encrypted and in this case we try to display something like "an encrypted file" as file name instead.

**Comment by marinofaggiana** [comment]
@nickvergessen ,for me work

**Comment by marinofaggiana** [comment]
> Do all encrypted files names follow the same pattern?
On android we use uuid: 2cb1a161-5f7c-4287-a419-2e160cc90c69

was without "-" ... ?

**Comment by tobiasKaminsky** [comment]
Right, sorry, we use:
9702f647197e42d991854361ed90e0a2
83f51a4e72a84c558eb18032cf4be331

but desktop seems to use:
P3sHabJlMdSDnHYo0kqH
re3gwioy2wHHFHr9KQEm
