### ISSUE TITLE
Encrypted Files become inaccessible when E2E App is enabled

### ISSUE THREAD

**Issue by tscs37** [nextcloud/end_to_end_encryption#47]
After updating to the latest 13.0.0 from the stable channel and enabling the E2E app from the store, files previously encrypted with the Serverside Encryption App become inaccessible with the following error:

```
OCA\DAV\Connector\Sabre\Exception\Forbidden: client not allowed to access end-to-end encrypted content
    /var/www/virtual/[redacted]/nextcloud-13.0.0/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 124: OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkUserAgent('Mozilla/5.0 (X1...', '[redacted]')
    [internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/virtual/[redacted]/nextcloud-13.0.0/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/virtual/[redacted]/nextcloud-13.0.0/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/virtual/[redacted]/nextcloud-13.0.0/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/virtual/[redacted]/nextcloud-13.0.0/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
    /var/www/virtual/[redacted]/nextcloud-13.0.0/nextcloud/remote.php - line 164: require_once('/var/www/virtua...')
    {main}
```

The files in question have **NOT** been encrypted with E2E and **are accessible when disabling E2E encryption** in the browser and any client. There are no E2E folders setup as none of my clients have updated to the appropriate versions *yet*.

The server runs on an up-to-date Ubuntu 17.10 with Nginx + FPM behind a HAProxy installation. The database is PGSQL and I used APCu and Redis for locking.

**Comment by tobiasKaminsky** [comment]
This is already fixed in next android release, which will come very soon.

**Comment by tscs37** [comment]
This is not a problem with the android client, this is an issue on all clients, though primarly on the web interface.

**Comment by sysoppl** [comment]
Agree, after fresh install of stable 13.0 and enabling server side enc and e2e I cannot delete files 

Error:
![errr](https://user-images.githubusercontent.com/30871217/35882275-e6825d84-0b83-11e8-808b-4f26d2191bfc.png)

Looks like disabling e2e temporarily and wait for update is only way to fix this.

**Comment by tobiasKaminsky** [comment]
@schiessle for the server part?

**Comment by sulliwane** [comment]
I probably have a similar issue, reported and described here https://help.nextcloud.com/t/linux-nextcloud-client-tech-preview-error/27034/2 (note : my android app seems to work perfectly with the E2EE encryption)

**Comment by tigernero79** [comment]
I think there is some bung in the end to end module, because the error it generates on files that are in the normal unencrypted folders, and both from web and from android application the problem exists.

so we know that you can not delete a file in an encrypted folder not yet at least.

but here we talk about files in normal folders.

if you deactivate the module, you will be able to delete the bug in the e2e server module

**Comment by schiessle** [comment]
this should fix it: https://github.com/nextcloud/end_to_end_encryption/pull/61, maybe you can apply this two line change and report back if it solves the issue for you: https://github.com/nextcloud/end_to_end_encryption/pull/61/commits/cb7e3b1ac51d65beb4a8d6bbdbb551ae02982fa7

**Comment by sysoppl** [comment]
Tried that, and I was able to delete files and folders, but I was not able to upload new files to e2e folder with error "you do not have permission to send to this folder" (android 3.0.1)
Server error:
![errore2e](https://user-images.githubusercontent.com/30871217/36314518-630a3f30-1335-11e8-8cea-ea7b69649933.png)
I was using default encryption module and e2e when testing.

**Comment by tigernero79** [comment]
https://github.com/nextcloud/android/issues/2189

same problem, turning off server side encryption now only thing I can not do is upload files to e2e folders

**Comment by schiessle** [comment]
@tigernero79 if I understood you correctly in another issue the fix mentioned above solved the problem for you, right? Or do you still have to disabe server-side-encryption?

**Comment by schiessle** [comment]
@tobiasKaminsky maybe you can check if you can re-produce the issue described by @sysoppl ? Thanks!

**Comment by schiessle** [comment]
I just tested it with the Android client 3.0.0 from f-droid and Server-Side Encryption next to End-to-End encryption worked just fine for me, together with the patch mentioned here: https://github.com/nextcloud/end_to_end_encryption/issues/47#issuecomment-366229849

**Comment by tigernero79** [comment]
@schiessle

**Comment by tigernero79** [comment]
the fact not upload files via Android app in folder e2e is a problem application Android or in this issue
