### ISSUE TITLE
Unlock folder without token leads to 404

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/end_to_end_encryption#479]
- have an encrypted folder
- DELETE lock without passing token as header
--> returns 404

Instead it should give a better error message

**Comment by artonge** [comment]
Not authorised ?

**Comment by tobiasKaminsky** [comment]
No. According to API it needs token, which is okay.
But 404 is then misleading.
Better would be a 412 precondition failed, with info that token is missing.

**Comment by artonge** [comment]
First part server side:
- [ ] https://github.com/nextcloud/server/pull/39164

**Comment by artonge** [comment]
Change done in https://github.com/nextcloud/end_to_end_encryption/pull/405
