### ISSUE TITLE
E2E not working on Pixel2XL device

### ISSUE THREAD

**Issue by Wizlonex** [nextcloud/end_to_end_encryption#48]
I successfully upgraded from 13 beta 4 to the first initial 13 release.
 
I have the E2E app enabled in my NC instance.

I am unable to enable encryption on mobile phone (Pixel2XL).  Whenever I try, I seem to successfully "retrieve keys" - I get the dialog box with a dozen phrases in.  I click "Set U Encryption" and it reports "generating keys" then it immediately fails and reports "Keys could not be stored, please try again".  I see the SAME ERROR on a different android device so I suspect it's either me being an idiot or a server setting?

No messages in Nextcloud server logs (not even at debug level).  No information in my stream relevant to the attempt (it shows I creted a test directory, then nothing else).

My Windows Desktop app does not have a setting for encryption (or if it does, I sure as heck can't find it - Version 2.3.3 (build 1) and "no updates" reported). 

I suspect I am doing something dumb, but if so at least you know the app is not idiot proof.

I am happy to provide any information you might be interested in.  My Nextcloud instance otherwise seems to work flawlessly other than one small but potentially important detail: since I am unable to enable E2E, I tried to enable server side encryption.  And even after logging out/in, I have not been given a chance to set encryption keys.  Maybe my whole install has something miss-set for encryption?

Either way, thanks for a SUPERB product - it's made my compliance issues and privacy concerns (I am a former OneDrive user...) practically disappear.  :-)

**Comment by mannp** [comment]
I am having the same problem on my first device I have tried to setup after a fresh install of NC13 and Android 3 release.

**Comment by tobiasKaminsky** [comment]
Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by ardevd** [comment]
@Wizlonex this is fixed with [this PR](https://github.com/nextcloud/android/pull/2154)

**Comment by tobiasKaminsky** [comment]
Please reply in android repository, if this still occurs with 3.0.1.
