### ISSUE TITLE
Deciphering using Bash + Mnemonic

### ISSUE THREAD

**Issue by ethicnology** [nextcloud/end_to_end_encryption#485]
**Is your feature request related to a problem? Please describe.**
It would be really usefull to have a simple CLI tool to decipher Nextcloud E2E Files using bash and the mnemonic

**Describe the solution you'd like**
```sh
$ nc-e2e decipher /path/to/folder
please enter your mnemonic:
```

**Describe alternatives you've considered**
[Asking the community](https://help.nextcloud.com/t/how-to-decipher-e2e-file-using-bash-mnemonic/166154)

**Comment by magicprograms** [comment]
This is necessary, files corrupted while updating E2EE enabled folder.
Decryption should be easy like this.

**Comment by ethicnology** [comment]
@yahesh started to work on it [here](https://github.com/nextcloud/encryption-recovery-tools)

> Hi, I’m the maintainer of the [encryption-recovery-tools 3](https://github.com/nextcloud/encryption-recovery-tools). I started working on the support of the end-to-end encryption, but it will probably take a bit longer till the first version is done as I have to translate the C++ code of the Nextcloud client to PHP that the recovery tools are written in.

**Comment by joshtrichards** [comment]
Added in nextcloud/encryption-recovery-tools#23
Docs are here: https://github.com/nextcloud/encryption-recovery-tools/blob/master/end-to-end-encryption/README.md
