### ISSUE TITLE
End to end encryption and decryption from the browser 

### ISSUE THREAD

**Issue by myomv100** [nextcloud/end_to_end_encryption#497]
Hello Everyone,

End to end encryption is one of the best features of nextcloud. However, it's currently not possible to access e2e encrypted files from web browsers. Fortunately, the term e2e has become increasingly popular in recent years. Today, a lot of web apps offer e2e capabilities directly from the browser wither it's file sharing, video conferencing, chat apps, etc.  The web cryptography api has developed nicely in recent years. So, I think we can enjoy full featured e2e capability for nextcloud directly from the browser without compromising nextcloud high security standards. 

I started to experiment with nextcloud E2EE app api and web crypto api. It wasn't very challenging to retrieve, encrypt/decrypt the metadata.  Also, signle files encrypt/decrypt on upload and download was not a big issue. What I think is a little bit difficult is how to organize the code and how to do most of the processing within the E2EE app instead of changing much in Files app. There might be some security concerns regarding key storage, cached data, file previews;  I think all of that can be secured with modern browsers. 

![image](https://i.ibb.co/DbY5MsF/ezgif-1-fa31ca0fb9.gif)

Best

**Comment by joshtrichards** [comment]
Did you close this because you moved the matter elsewhere or... ?

**Comment by myomv100** [comment]
I closed the issue, so I have more time to think about the feature with less interruptions. I was planning to reopen it again with reference to a working solution. 

Feature status as following:

#### Barely works:
- Prompting the user for Mnemonic words and use ot for the decryption of user encryption keys.
- Decryption of files metadata (filenames, mime types) and display it in the file app .
- Ability to  download a single file with content and metadata decryption. 
- Ability to  download multiple files or a directory  (Zipped)  with content and metadata decryption.  This is tricky a little bit. The browser unzips, decrypts and rezip and serves the file again to the user. 

#### Todo
- Storing the metadata in the localStorage of the browser so you don't fetch any files metadata twice in as long as you are logged in.
- Upload files to an E2E encrypted folder..

#### Challenges
- Dealing with zipped files of encrypted files that have many subfolders can  the overwhelm user machine and eat up a lot of CPU time..
- Generating previews now happens on the server.. In our case, it will happen at the user side.. When you open a folder, all the Photos, Videos, TXT and PDF should be downloaded to allow previews generation. They could be stored in the localStorage too. 
- Keeping everything secure while it is cached in the browser.


Best!

**Comment by aero4** [comment]
Hi @myomv100!
Is there any update to this feature?
I would love to see E2EE folder being accessible using the web browser!

**Comment by joshtrichards** [comment]
@myomv100 May be interested in recent updates here:

nextcloud/server#49649
And #822
