### ISSUE TITLE
Publish version for NC 28

### ISSUE THREAD

**Issue by tflidd** [nextcloud/end_to_end_encryption#527]
There is already a stable branch for NC 28 but a version on the app store is still missing. With the release candidates out, it would be great to test as many apps before the official release....

**Comment by eibex** [comment]
NC28 is released and E2EE is not ready yet again. Why is this a featured app?

**Comment by eibex** [comment]
NC28 is released and E2EE is not ready yet again. Why is this a featured app?
I made the mistake of updating all my dockers without triple checking Nextcloud app compatibility and now I'm locked out of my files.

I really appreciate the work put forth in the app, especially in the past months, but there is a massive discrepancy between communication and the software itself.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/end_to_end_encryption/releases/tag/v1.14.0
