### ISSUE TITLE
Updated NC from 27.x to 28 and lost my data

### ISSUE THREAD

**Issue by JP95Git** [nextcloud/end_to_end_encryption#528]
My current situation before Nextcloud killed my data:
Having Nextcloud for Windows installed and had several folders (including %APPDATA%) synced with E2E enabled.

### Steps to reproduce
1. Update Nextcloud from 27.x to 28 using the web interface. Read something about some plugins which were not updated yet (including E2E). 
2. Windows client 3.10.2 was still running
3. After the update most of my synced files in Windows were replaced with random filenames like "0b9a5cf2c7514883878deb32902427a7" and random content. Unfortunately my %APPDATA% is totally gone, so I lost access to KeePass and access to Nextcloud.

I have to get my external backup drive and restore all my files. Once I got access to my profile again, I can fill the remaining fields in this ticket. But this should not happen!!!

### Expected behaviour
No loss of data

### Actual behaviour
Most of my files are gone or replaced with something like "0b9a5cf2c7514883878deb32902427a7" and random content.

### Server configuration

**Operating system:**
Windows 10 Pro

**Web server:**
Apache 2

**Database:**
MariaDB 10.11.4

**PHP version:**
8.2.13

**Nextcloud version:** (see Nextcloud admin page)
27.x, than 28.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update to 28

**Where did you install Nextcloud from:**
Using the update from the web interface.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

If not, provide at least the version number of the End-to-End-Encryption app.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

### Client configuration
**Browser:** Firefox 120.0.1

**Operating system:**
Windows 10 Pro

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tflidd** [comment]
The app was not yet released for NC28:
https://github.com/nextcloud/end_to_end_encryption/issues/527

**Comment by JP95Git** [comment]
I was able to recover my files from backup.

I had several folders synced with E2E. Only my synced %APPDATA% folder was deleted. I found some of the deleted files in my trash bin. But it was easier to just recover everything. I disabled the Nextcloud Client.

Logs could be a problem. I found several issues with Nextcloud. Logs is one of the issues. I got 161 logfiles with 120 MB just for one day. So I usually delete the logs, because Nextcloud filled my C partition with logs and temp files several times. I will report this soon. The 120 MB logs are from the issue.

Even without logs, this happened:
- APPDATA had changed, Nextcloud started to sync the folder.
- I upgraded Nextcloud to 28 and did not noticed that E2E is not yet available.
- The Nextcloud Windows Client was not aware of this too.
- The client saw some changes on the server and synced all encrypted files back to my devices. So it deleted all files and replaced them with their encrypted form.
- More changes happened in APPDATA. Nextcloud client synced them to online without encrypting anything. My APPDATA on my server has now my old encrypted files and some unencrypted files.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/end_to_end_encryption/releases/tag/v1.14.0

**Comment by JP95Git** [comment]
This nice update was my final nail for the coffin of Nextcloud. 

After enabling E2E in v28 nothing changed. The user, which was used for sync was totally stuck. Perhaps because I had one folder "Mozilla" without E2E and the same folder with E2E but with different content. As you can only delete content after a successful sync, which did not work, I were in a deadlock. I had to delete the user and create a new one. Unfortunately the Windows client was no longer able to detect the E2E app, so E2E was unavailable, for ALL users!!! So I uninstalled Nextcloud from Windows and deleted all settings. Perhaps Nextclouds E2E will be in a more stable state in some years.
