### ISSUE TITLE
 How can I display the 12 word key E2E on android apps?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/end_to_end_encryption#53]
I have two android phones with nextcloud installed on the first access to encrypted folder and not having marked the key on the second mobile with the same account asks me the password to access the same folder?

I do not remember how I can do it? on app ios of a friend of mine there is voice display key would serve a function like that to remember it, or there is a way to get it back or reset it?

**Comment by schiessle** [comment]
If you didn't wrote it down there is no way at the moment to access it, afaik. But I would recommend to ask in the corresponding client repository.
