### ISSUE TITLE
Prevent (or warn) when E2EE is enabled at the same time as SSE

### ISSUE THREAD

**Issue by joshtrichards** [nextcloud/end_to_end_encryption#533]
Since they're incompatible currently.

Unfortunately as far as I can tell there's no way to specify in the `appinfo/info.xml` for this and the `encryption` app a way to prevent them from being enabled in parallel. In addition, since most interaction occurs client-side, simply returning 4xx codes won't necessarily give the appropriate visibility to any error/warning message when attempting to perform encryption related options.

Some ideas:

- Add a setup check under Admin Overview
- Add a post installation check that causes all E2EE client requested operations to basically be blocked (not friendly but at least keeps things from getting screwed up to start with)
- Add functionality to apps store/app metadata to support specifying apps that aren't compatible with each other
- Add a check in *both* this app and the `encryption` app that warns during any UI or CLI settings operations/interactions that the *other* app was detected and that the user has an invalid deployment/configuration
- ?

**Comment by sorbaugh** [comment]
Many good ideas here that each have merit on their own and since many people seems to running into this "trap", maybe we can at least start with adding a WARNING text. What do you think @artonge ?

PS: The long term solution will be to make both SSE and E2EE compatible with each other.

**Comment by karlemilnikka** [comment]
According to the [Nextcloud 30 (Nextcloud Hub 9) presentation video](https://youtu.be/EnT_OVfE4nw?si=cSZGo6kiGHCJzNpc&t=1442), E2EE shall now be possible to use in conjunction with SSE. Please note that the E2EE app hasn’t been updated for Nextcloud 30 yet.

**Comment by artonge** [comment]
I just released a version for 30

**Comment by artonge** [comment]
My bad, there was an error in the release

**Comment by artonge** [comment]
Done :partying_face:
