### ISSUE TITLE
Unable to remove or decrypt e2e encrypted folder under e2e encrypted folder app  android

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/end_to_end_encryption#54]
I noticed that if I create an e2e encrypted folder from android application and inside it create a folder the application itself makes me exit again crypt folder entry, but it should not be already encrypted by default being a sub folder? and in any case it does not allow me to erase it and I come to say decripta does not decrypt it

**Comment by schiessle** [comment]
If a folder is marked as encrypted everything below is encrypted, including sub folders.
