### ISSUE TITLE
App should return 409 when private key already exists

### ISSUE THREAD

**Issue by ardevd** [nextcloud/end_to_end_encryption#57]
Currently, the app will return 409 if a public key already exists. This is a very useful property, however it wont account for existing private keys. I think it should return 409 if a private key exists as well.

Also, how about returning a json field with a value indicating why 409 is returned?

**Comment by tobiasKaminsky** [comment]
About which endpoint do you talk about?
[Store API](https://github.com/nextcloud/end_to_end_encryption/blob/master/doc/api.md#store-private-key) says:
409 conflict: if a private key for the user already exists

**Comment by ardevd** [comment]
Ah, my bad. I overlooked that one. I realize now that perhaps the issue was with the Android app but I tried the following:

1. Post a new keypair to the E2E app.
2. Delete the public key
3. Re-install the Android app. It will then prompt you to generate a new pass phrase. After which it posts the keypair to the server again where the E2E app seemingly ignores the private key (seemingly because it already exists) and then accepts the public key. The end result is a keypair mismatch.

Hope this made sense.

From the API point of view it makes sense that the behavior is this way. But the end-result is flawed. Im thinking the Android app should probably not upload the public key if the private key was rejected.

**Comment by ardevd** [comment]
UPDATE: Looking through the Android app code I see that it does in fact check the return value when posting the private key. That means that the server seemingly returned 200 OK even though a private key already existed.

**Comment by tobiasKaminsky** [comment]
We first generate/use the public key and only if the public was stored correctly on server, we continue with private key.
Isn't this solved via #2153?

**Comment by ardevd** [comment]
Yes, though in my testing the server returned 200 OK even though a private key already existed. I will do some more testing and see if I can reproduce the issue.

**Comment by georgehrke** [comment]
@ardevd Were you ever able to reproduce the issue?
