### ISSUE TITLE
Can not install : Index name "id" for table "oc_bookmarks" collides with the constraint on table "oc_e2e_encryption_lock"

### ISSUE THREAD

**Issue by GillesMocellin** [nextcloud/end_to_end_encryption#587]
### Steps to reproduce

1. I'm using Nextcloud 28.0.3 via Docker image stable-fpm tag
2. Try to install Tables app
3. I have the error Index name "id" for table "oc_bookmarks" collides with the constraint on table "oc_e2e_encryption_lock"

### Expected behavior

Application is installed an active

### Actual behavior

Application is installed but inactive, cannot activate

### Tables app version

0.6.6

### Browser

Firefox 123

### Client operating system

Linux (Ubuntu 22.04)

### Operating system

Debian 12

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

MariaDB

### Additional info

Nextcloud Community Docker image, tag stable-fpm, from https://hub.docker.com/_/nextcloud/

**Comment by juliushaertl** [comment]
Also FYI @marcelklehr for bookmarks

**Comment by szaimen** [comment]
> This doesn't look related to the tables app. I'll move it to the e2e encryption app for checking.
> 
> @szaimen I thought this should have been softened with 28.0.3 already by [nextcloud/server#43357](https://github.com/nextcloud/server/pull/43357)

I cant tell if this is also the case with app installs... Cc @nickvergessen

**Comment by nickvergessen** [comment]
Ah, any install will trigger the failure at the moment it seems 🙈 
Should only check "new" identifiers, not all identifiers in the new schema :/

**Comment by marcelklehr** [comment]
So, is this usage wrong? Do I need to change something?

https://github.com/nextcloud/bookmarks/blob/master/lib/Migration/Version000014000Date20181002094721.php#L97

**Comment by nickvergessen** [comment]
Well for autoincrement like the id it should have a different name anyway. I will check again on Monday

**Comment by nickvergessen** [comment]
At least for e2ee the index is *not* autoincrement, so it should have a better name...

**Comment by GillesMocellin** [comment]
Still present in today upgrade from 28.0.? to 29.0.4.1

**Comment by Chartman123** [comment]
This also seems to affect Forms: https://github.com/nextcloud/forms/issues/2346

**Comment by joshtrichards** [comment]
> Edit: Seems like it was caused by some remnants of a previously installed e2e app :)

Indeed. This hasn't been a thing since v1.13.1 (#427).
