### ISSUE TITLE
Basic encryption module

### ISSUE THREAD

**Issue by KovalevArtem** [nextcloud/end_to_end_encryption#59]
What passwords do I enter here? I do not understand ...
![screenshot-192 168 1 217-2018-02-15-11-24-00](https://user-images.githubusercontent.com/36500228/36247339-b2339f58-1244-11e8-9bd0-3ca238099ee8.png)
What password to enter here: Old log-in password ?
What password to enter here: Current log-in password ?

**Comment by tobiasKaminsky** [comment]
This is not related to E2E.
@schiessle is this server side encryption?

**Comment by KovalevArtem** [comment]
![screenshot-192 168 1 217-2018-02-15-12-41-41](https://user-images.githubusercontent.com/36500228/36250010-9a5a3fbe-124d-11e8-8ddd-c3f7608da7d4.png)
How to solve this problem?

**Comment by anviza** [comment]
> How to solve this problem?
Disable "Default encryption module".
@tobiasKaminsky @schiessle Is it needed for E2E?

**Comment by tobiasKaminsky** [comment]
E2E is a separate app: https://apps.nextcloud.com/apps/end_to_end_encryption

**Comment by schiessle** [comment]
@KovalevArtem  That's a setting from the server-side encryption. Doesn't has to do anything with end-to-end encryption. This happens once your password was changed on a external user back-end, e.g. LDAP. In this case you need to enter your old login password and your new login password so that the password of your private key match again your login password

**Comment by KovalevArtem** [comment]
@schiessle 
Thanks for the info...
I realized that my question is not related to E2E.
![screenshot-nextcloudpi local-2018-02-17-16-37-52](https://user-images.githubusercontent.com/36500228/36341601-df6200c8-1401-11e8-85c7-db35d3ad9ecf.png)

But I still can not understand my question ...
After I installed the End-to-End application, Encryption

I still can not encrypt the folder ... I tried to do this in the client for Windows, MacOS, Ubuntu ...

Nowhere does it appear:
![screenshot-nextcloud com-2018 02 17-16-42-27](https://user-images.githubusercontent.com/36500228/36341597-caeaba0e-1401-11e8-8ac9-48c8f837632e.png)

And, accordingly, I can not do this:
![screenshot-nextcloud com-2018 02 17-16-43-02](https://user-images.githubusercontent.com/36500228/36341598-cd8bbcd6-1401-11e8-9de0-5af18dce849e.png)
(Screenshots from the official video)

What is the problem?

**Comment by tobiasKaminsky** [comment]
@KovalevArtem do you use the newest desktop client: https://download.nextcloud.com/desktop/prereleases/E2E/ ?
