### ISSUE TITLE
iOS Create PublicKey

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/end_to_end_encryption#6]
Hi boys, where are the specification of : 

curl -X POST http://<user>:<password>@nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/public-key -H "OCS-APIRequest:true" -d csr="<urlencoded-csr>"

1) urlencoded ... type ?? 
2) I thing without -----BEGIN PUBLIC KEY----- and -----END PUBLIC KEY----- 

@tobiasKaminsky @schiessle 

thanks

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md#initial-device
or
https://github.com/nextcloud/end_to_end_encryption/blob/master/doc/api.md#sign-public-key
both say urlencoded.

This is how I do it on android:
https://github.com/nextcloud/android/blob/3f9b0dfbb6d65107ea6e34eb5a0b8301b43d6736/src/main/java/com/owncloud/android/utils/CsrHelper.java#L58-L58

**Comment by marinofaggiana** [comment]
Thanks @tobiasKaminsky but for me "generateCsrPemEncodedString" is incompressible  :D 

return "-----BEGIN CERTIFICATE REQUEST-----\n" + android.util.Base64.encodeToString(
                derCSR, android.util.Base64.NO_PADDING | android.util.Base64.NO_WRAP)
                + "\n-----END CERTIFICATE REQUEST-----";

1- why BEGIN CERTIFICATE REQUEST the CSR is -----BEGIN CERTIFICATE----- 
2- why Base64 encode (the public key) and not the "-----BEGIN CERTIFICATE REQUEST-----"
3- and then ?
4- sorry this is not clear for me :(

Please  write a specification document  ... I don't know Java Android, for me it's only several time loss.

**Comment by tobiasKaminsky** [comment]
According to https://ssl-trust.com/csr-erstellen/openssl I created a CSR with
> openssl req -nodes -new -newkey rsa:2048 -sha256 -out csr.pem

and this is the result:

>-----BEGIN CERTIFICATE REQUEST-----
MIICijCCAXICAQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUx
ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAMYJRw5TgoatRjD4fnmPYNNrIpqg0tG45U+wOewo
kUtwW+UgjvihW9h+JWmx2zmcjE+q6BoxHJH+aHkrGu3qs9ub60AUHR3A/MCz3Sia
b9YpyD5EuViqaWIpsQbWhI+1XhUVLhMEyxAFVpX5+NDVPszWBzKdQwKilbP0jjd8
em+gbK30OiLRg8BpQL3VWI/Cw8oSwlMNy7HVUT5YFrvRh2XXcMbamBcjR+AEGiNg
RSFFZ6wIWiqZCIDax72UprwmrPbjQj9cHJu+7bljLD1Hj6yPvvCu7Z+94G/eopdA
lDJZExCNwAs2ahdf/whnlRJLU3Swb4T8VpCQuqJ+sttYmscCAwEAAaAAMA0GCSqG
SIb3DQEBCwUAA4IBAQAnMI1InLhxzOeG65zFXWGuDp+8Yf4WHGcaI1MYtsihRL/i
VK9fEH73f2o2scDzM8R17Q82xdVRevE+9UjHmXyfe/tiL5d9kbJ6+fb8eyqGaoqP
VxliswvSm2mCfBvFeUIaGxWdjAAkcRClP4+13uFIDR09pwN7xP6QrCh7dE+fhIf4
bM+oyDZ/TtTjlDXT1jkpUWIUP/M2SPmFPamzP7RsA3dTAy3Erk8onrYzrD26rtR6
7XMEiA78pzOXFKPwRh47eZkdsLZgVtYFgMXubwL6HgxRWcCTP2mJMse5Dzxy9BG6
R19dl3u9F/kHu0z1ZA3j22PTKA1ryEqtG8lEdszh
-----END CERTIFICATE REQUEST-----

2.: this is the standard form of a CSR.
3: ?

**Comment by marinofaggiana** [comment]
can you write here the -----BEGIN CERTIFICATE REQUEST-----
MIICijCCAXICAQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUx
ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAMYJRw5TgoatRjD4fnmPYNNrIpqg0tG45U+wOewo
kUtwW+UgjvihW9h+JWmx2zmcjE+q6BoxHJH+aHkrGu3qs9ub60AUHR3A/MCz3Sia
b9YpyD5EuViqaWIpsQbWhI+1XhUVLhMEyxAFVpX5+NDVPszWBzKdQwKilbP0jjd8
em+gbK30OiLRg8BpQL3VWI/Cw8oSwlMNy7HVUT5YFrvRh2XXcMbamBcjR+AEGiNg
RSFFZ6wIWiqZCIDax72UprwmrPbjQj9cHJu+7bljLD1Hj6yPvvCu7Z+94G/eopdA
lDJZExCNwAs2ahdf/whnlRJLU3Swb4T8VpCQuqJ+sttYmscCAwEAAaAAMA0GCSqG
SIb3DQEBCwUAA4IBAQAnMI1InLhxzOeG65zFXWGuDp+8Yf4WHGcaI1MYtsihRL/i
VK9fEH73f2o2scDzM8R17Q82xdVRevE+9UjHmXyfe/tiL5d9kbJ6+fb8eyqGaoqP
VxliswvSm2mCfBvFeUIaGxWdjAAkcRClP4+13uFIDR09pwN7xP6QrCh7dE+fhIf4
bM+oyDZ/TtTjlDXT1jkpUWIUP/M2SPmFPamzP7RsA3dTAy3Erk8onrYzrD26rtR6
7XMEiA78pzOXFKPwRh47eZkdsLZgVtYFgMXubwL6HgxRWcCTP2mJMse5Dzxy9BG6
R19dl3u9F/kHu0z1ZA3j22PTKA1ryEqtG8lEdszh
-----END CERTIFICATE REQUEST-----

after urlencoded  and ready for sent to API ? I think this is the issue, the URL conversion 

Thanks @tobiasKaminsky

**Comment by marinofaggiana** [comment]
P.S: strange with my openSSL the output is -----BEGIN CERTIFICATE-----

**Comment by oparoz** [comment]
@marinofaggiana Look at the CSR file, not the certificate

**Comment by marinofaggiana** [comment]
yes yes example this is my output 

cat e2e_certificate.pem 
-----BEGIN CERTIFICATE-----
MIIDNDCCAhwCAXswDQYJKoZIhvcNAQELBQAwYDELMAkGA1UEAwwCbmMxHjAcBgNV
BAsMFUNlcnRpZmljYXRlIEF1dGhvcml0eTESMBAGA1UECgwJTmV4dGNsb3VkMRAw
DgYDVQQHDAdWaWNlbnphMQswCQYDVQQGEwJJVDAeFw0xNzEwMTIxMjA4MzlaFw0y
NzEwMTAxMjA4MzhaMGAxCzAJBgNVBAMMAm5jMR4wHAYDVQQLDBVDZXJ0aWZpY2F0
ZSBBdXRob3JpdHkxEjAQBgNVBAoMCU5leHRjbG91ZDEQMA4GA1UEBwwHVmljZW56
YTELMAkGA1UEBhMCSVQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDU
USdsy3hnRWKnNnlYMnUl2tm8qtmeC5j9rI+2nAtTs0wXsXwAiNzCpbrb+XPtEtuF
ZE8y376ZsPsXNHiilRqSreZ3TNB9OcjrV7UFiSmCEDY1pHG5g1smSRlb5Kvkv0LK
G5PFXRHfXX9agRTsPeb3gqHex06cewMs0EhURlf0nL6hpT2W3swBiwQWfI4AAbOM
MeeYfoo6n60BJr0JvBpfDzq4xfzFUTgeeS+ShMAhdhmnQVOU7INDzOpTZny+KsLY
Vb+G4V0x6UnSJEWhAnw7iMfqfoH/DR0/p2K5C2aHilP6sxt77XtMhuG7VNViXiR0
C07FTq+jcDfqrQV/TIsLAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEOo4hDOxala
nBWXORDZF7sBKRHknyU2bXSSSEqFoSlQlxkeZiusMwCfDEkzg2eViFl9maO5HceO
6vF4+mmeevhoSsITEvaZi73yDRzJ79YtqLPiakpK9nKfa6DlIkRFPcJb7PbCMzFC
p0T5d86pLqiP4mmHGHRROQVHgCANvHcvXd3BUqWrkGqQX0lwaG4NLHXo/SL9T/X/
koCxf2ybkP9rXeY+3yN0KQVFjqheDx//l0OoJ7MjKocgBipeXaogpYFdxAMb2olF
iPa4A7ftHZhqaUune5P0qAeVJH85Ca2MGyArRJlHi8yBkxvuQclnVQsaMUQSmlb1
exBqeCT3L60=
-----END CERTIFICATE-----

**Comment by marinofaggiana** [comment]
@tobiasKaminsky a question : 

public static String generateCsrPemEncodedString(KeyPair keyPair) throws IOException, OperatorCreationException {
        PKCS10CertificationRequest csr = CsrHelper.generateCSR(keyPair);
        byte[] derCSR = csr.getEncoded();
        return "-----BEGIN CERTIFICATE REQUEST-----\n" + android.util.Base64.encodeToString(
                derCSR, android.util.Base64.NO_PADDING | android.util.Base64.NO_WRAP)
                + "\n-----END CERTIFICATE REQUEST-----";
    }

why encodeBase64 the CSR without -----BEGIN CERTIFICATE REQUEST-----\n and "\n-----END CERTIFICATE REQUEST-----" ?? and not all CSR ?

Thanks
