### ISSUE TITLE
After enabling E2E encryption, no permission to write data in folder

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/end_to_end_encryption#60]
Hi,

I'm using the Nextcloud 3.0.1 client on Android 7.1. A Nextcloud 13 server on Ubuntu 16.04. I installed the E2E app manually since it was not available in the default app listing on the server (by extracting the tar.gz in the apps folder and changed the permissions to the www-data user). Then I enabled the app in the apps settings. I have the option now in my Nextcloud client on Android. But after I enable the encryption option, I'm unable to upload files or create folders. What could be the problem here? I already removed the Nextcloud user and recreated the user. Same problem. Some screenshots below.

![screenshot_20180215-142809](https://user-images.githubusercontent.com/6113099/36258927-c84c40d4-125c-11e8-9a5e-94c37ee534d0.png)
![screenshot_20180215-142817](https://user-images.githubusercontent.com/6113099/36258928-c86aae20-125c-11e8-996d-3dfba2e43d52.png)
![screenshot_20180215-142828](https://user-images.githubusercontent.com/6113099/36258929-c888d044-125c-11e8-9149-23a0739bc82c.png)
![screenshot_20180215-142831](https://user-images.githubusercontent.com/6113099/36258931-c8aa093a-125c-11e8-9e31-0e6912746db5.png)

**Comment by tobiasKaminsky** [comment]
Once you marked a folder as encrypted, you should see an e2e setup on first enter.

**Comment by AquaL1te** [comment]
@tobiasKaminsky this is indeed the case, but then when I enter the directory and want to upload a file or create a directory, I get the error of the last screenshot. [Here](https://cloud.neobits.nl/s/aVPgEzdO4gXR0dc) is a screen recording. Do you have any troubleshooting suggestions? The server is freshly installed, so no old caches are present of previous Nextcloud installations or anything like that. The manual installation of E2E as described in the first post of this thread is correct? There is not yet an official installation available?

**Comment by tigernero79** [comment]
@tobiasKaminsky 

same problem described here:

https://github.com/nextcloud/android/issues/2189

the key has already been stored correctly,
but when attempting to upload or delete a file in an encrypted folder, the operation is denied

**Comment by fti7** [comment]
Same here :-( 
No Server Side Encryption enabled

**Comment by sorcer1122** [comment]
I have got the same problem. After I first enabled the encryption, I was prompted to write down my 12 words password and after that I was not able to upload anything into the encrypted folder until I switched the encryption off.

Server side encryption is disabled.

**Comment by tobiasKaminsky** [comment]
@AquaL1te the app is available in app store: https://apps.nextcloud.com/apps/end_to_end_encryption

@AquaL1te @fti7 @sorcer1122 
Can one of you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by tigernero79** [comment]
tobias you have my test data, sent via nero79@msn.com username is tobias password is written in the email url is www.pensierando.it/Nextcloud

**Comment by tigernero79** [comment]
do you need to re-send your data by email or can you find them?

**Comment by AquaL1te** [comment]
@tobiasKaminsky I've indeed installed the app from that link indeed and extracted it in the /apps directory. I wanted to confirm that it was the right install method, since "normal" apps are included in the Nextcloud app store.

I did a complete wipe of my mysql database and extracted a fresh installation of Nextcloud 13. When I now log into the Android client and set a folder as encrypted I don't get the 12 security words for recovery. I'll send you credentials to login, but it's a test machine for educational purposes, it's state could be variable.

**Comment by vincentadultman** [comment]
I can confirm this bug with the following reproduction path, on Ubuntu server.

snap install nextcloud --channel=13/candidate
Add trusted domain
nextcloud.enable-https lets-encrypt

Within server admin area, install end to end encryption app from app store.
Create a user to test.

Download nextcloud android app. 
Login as test user in app.
Create new folder, mark as encrypted.
Enter the folder, encryption passphrase is presented.
On trying to upload a file, or create a folder "you are not permitted to upload in this folder / You are not permitted to create this file"

Errors are created in log on server, for example on trying to create a sub-folder

`{"reqId":"CfDJaeBFIYNsWEXPhGE7","level":4,"time":"2018-02-24T11:45:13+00:00","remoteAddr":"myiphere","user":"myuser","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/MyFolder\/Testy\/","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client not allowed to access end-to-end encrypted content\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/snap\\\/nextcloud\\\/5119\\\/nextcloud\\\/extra-apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php(124): OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkUserAgent('Mozilla\\\/5.0 (An...', '\\\/MyFolder')\\n#1 [internal function]: OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/snap\\\/nextcloud\\\/5119\\\/htdocs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/snap\\\/nextcloud\\\/5119\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/snap\\\/nextcloud\\\/5119\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/snap\\\/nextcloud\\\/5119\\\/htdocs\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/snap\\\/nextcloud\\\/5119\\\/htdocs\\\/remote.php(164): require_once('\\\/snap\\\/nextcloud...')\\n#7 {main}\",\"File\":\"\\\/var\\\/snap\\\/nextcloud\\\/5119\\\/nextcloud\\\/extra-apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":169}","userAgent":"Mozilla\/5.0 (Android) `ownCloud-android\/3.0.1","version":"13.0.0.14"}

**Comment by 80tf3262p8** [comment]
Go back to the 3.0.0 client and try it. The 3.0.1 client changes the user agent for some reason and the server is picky about that. See my comment here: https://github.com/nextcloud/android/issues/2189#issuecomment-368427882

**Comment by tobiasKaminsky** [comment]
3.0.2 released, please re-open if this problem persists.

**Comment by tigernero79** [comment]
in play store was released? it still does not appear to me as an update. I have active beta tester mode.

**Comment by tobiasKaminsky** [comment]
I released it 10min ago. Usually it takes at least 30mins to get it published and then some time to get it distributed on all devices.

**Comment by tigernero79** [comment]
I have tested nextcloud 3.0.2 application and all is well the bug has been fixed, it is possible to delete files in the encrypted folder but not yet however the encrypted folders inside the parent folder say. a atra what will you implement the ability to view the 12 words e2e in the application as already happens with application for ios?

**Comment by tigernero79** [comment]
I said this problem here, what version will be implemented?

https://github.com/nextcloud/android/issues/2128

confirm that with android application I can not delete folders inside a compressed folder but only files?
