### ISSUE TITLE
If default encryption and E2E App are enabled it is not possible to edit/delete files encrypted by the default encryption module

### ISSUE THREAD

**Issue by holzhannes** [nextcloud/end_to_end_encryption#63]
If you have both enabled the default encryption and the E2E App and you upload a new file you will see an error message: ```Die Datei konnte nicht erstellt werden ""``` in English ```The File could not be created ""``` if you reload the page you will see the file but you are not able to delete or edit it. You will just see a message ```Error deleting the file ...```. If you disable the E2E App it is possible to delete the File.

**Comment by tigernero79** [comment]
discussion here already open

https://github.com/nextcloud/end_to_end_encryption/issues/60

**Comment by schiessle** [comment]
Should be fixed with the Nextcloud Server app version 1.0.4 and the Android app 3.0.2
