### ISSUE TITLE
E2EE Android 3.02 Pasword fails and Android dev 20180302 allows access but no uploads allowed

### ISSUE THREAD

**Issue by mannp** [nextcloud/end_to_end_encryption#65]
Using Android 3.02 I am unable to get past the password request for the encrypted directory, that I previously had access too.

I have tried the dev android app and it accepts the password, but does not show any of the encrypted files uploaded with the iOS client and uploads error out too.

The same error occurs for both; 

Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\Forbidden: client not allowed to access end-to-end encrypted content/config/www/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 125:  OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkUserAgent('Mozilla/5.0 (An...', '/Data')[internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:  Sabre\Event\EventEmitter->emit('beforeMethod', Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:  Sabre\DAV\Server->exec()/config/www/nextcloud/remote.php - line 164:  require_once('/config/www/nex...'){main}
-- | -- | --

**Comment by schiessle** [comment]
@tobiasKaminsky can you reproduce it? Seems like the client sends the wrong user agent string

**Comment by schiessle** [comment]
@mannp it would be also useful to have detailed steps to reproduce it. If you could access the encrypted folder before, did you changed anything? Update the server app? Updated the Android app?

**Comment by schiessle** [comment]
@mannp seems like I can reproduce it... Will come back to you if I know more

**Comment by schiessle** [comment]
Seems like the Android client sends the wrong user agent string... let's continue here: https://github.com/nextcloud/android/issues/2314

**Comment by schiessle** [comment]
@mannp as a quick test you could try the Android app version 3.0.3 if you can install it via google play and report here https://github.com/nextcloud/android/issues/2314  if it solves the problem.

**Comment by mannp** [comment]
@schiessle will try now and report back :)

**Comment by mannp** [comment]
@schiessle I cannot tell if your change is working as I have too many locked files, and nc clients are complaining at 12 files being locked which are not part of E2EE.

Until I understand why they have not gotten locked I cannot issolate this one issue out.
