### ISSUE TITLE
[Bug]: No option to share E2EE folder with other users

### ISSUE THREAD

**Issue by Extarys** [nextcloud/end_to_end_encryption#671]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud website state it is possible to share E2EE folders, but no such option exists in real life.
![image](https://github.com/nextcloud/server/assets/11581433/f083b7d3-5f5a-4426-8c58-a66ab9141fc7)

### Steps to reproduce

1. Create a folder
2. Enable E2EE
3. Encrypt that folder using the Desktop client
4. No option to share that folder appears on the Web UI

### Expected behavior

Like a normal folder, a share option should be visible.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

The same page also states it's possible to File Drop into an E2EE folder, but that option is also not available in the UI.

**Comment by joshtrichards** [comment]
> No option to share that folder appears on the Web UI

E2EE isn't relevant to the Web UI by definition since the server has zero access to your data with E2EE.

Share from one of your configured clients.
