### ISSUE TITLE
Plain Directory structure

### ISSUE THREAD

**Issue by gdelacruz** [nextcloud/end_to_end_encryption#70]
Hello,

I've seen if the server is compromised, the directory structure of an encrypted folder will be compromised too.

I've seen in the paper this:

> Access to ciphertext must not leak directory structure nor file names or content.
> • Leaking the number of files in an encrypted folders is an accepted risk

Perhaps it's expected in future milestones, but, is it a bug or a non implemented yet feature? Or have I misunderstood this?

Thanks!

**Comment by tobiasKaminsky** [comment]
With cipertext the content of metadata json file is meant.
If you have access to the server, then you (as an attacker) can see the directory structure and how many files in each directory are, but not the content.

As far as I know it is not yet planned to hide the directory structure, @schiessle?

**Comment by ntimo** [comment]
Will the plugin encrypt the folder name in the future? So a attacker can not guess what is in a folder from knowing the folder name?

**Comment by woefe** [comment]
v2 of end-to-end encryption will have encrypted folder names. See the v2 branch on the [RFC repo](https://github.com/nextcloud/end_to_end_encryption_rfc/blob/v2/RFC.md#create-metadata-file).

**Comment by luixxiul** [comment]
rfc v2 being worked on here: https://github.com/nextcloud/end_to_end_encryption_rfc/pull/40
