### ISSUE TITLE
Data uploaded with nc-android app (e2e) and downloaded with nc-client (e2e) not readable

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/end_to_end_encryption#71]
Hi,

I use the nextcloud _android app_ with e2e-support and _nc-client_ (e2e) on Windows. 
I noticed the behavior that the windows-client is hanging (status syncing) when using encrypted folders on the server and data transfer between both apps produces non readable data: When I upload data with the android app an download it via client on my pc the a part of data/files is still encrypted and not readable. In the backgroud a nc 13.0.1 server is running.

Here is mentioned **not** to use server-side-encryption:
https://help.nextcloud.com/t/where-can-i-find-the-clients-that-do-e2e/28072

Is this right?
Do you need some log files?

Thanks!

Regards

**Comment by tobiasKaminsky** [comment]
The current client is still under heavy developement.
@rullzer @tcanabrava

**Comment by joergister** [comment]
With the Version of the end2end encryption plugin for nexcloud being beyond 1.0 I would expect that most of the stuff works out of the box. Sadly that is not the case.
- putting Data into an end2end encrypted folder on my laptop and sync it to my server works as expected.
- I can also view and edit these files on my android device (after I entered the mnemonic. 
-  But Data I create on my android device is not readable on my computer after being synced. (also files that are in the encrypted folder and that I edited on my smartphone are not)


(Android client Version 3.4.1 & Desktop Version 2.5.1 Appimage from the nextcloud website). 
Server Software Nextcloud 15.0,    End2End encrytion plugin V. 1.1.0)

The Nextcloud tech preview for end2end (https://download.nextcloud.com/desktop/prereleases/E2E/) does not work at all. I already have encrypted files on the server but they are not synced to my laptop and the error "could not read system exclude file" is given instead.

**Comment by georgehrke** [comment]
@misch7 @tobiasKaminsky Could you help me triage here please, so we can figure out whether this in an issue in Android, desktop or server? :)

**Comment by georgehrke** [comment]
bump @misch7 @tobiasKaminsky :)

**Comment by Dennis360ict** [comment]
Does this still happen with the [2.7beta3](https://nextcloud.com/blog/2-7-beta-3-of-the-desktop-client-is-ready-for-testing/) client?

**Comment by georgehrke** [comment]
It shouldn't. If it still does, please open a new issue and __fill the entire__ issue template. Thx

**Comment by spackmat** [comment]
Thank you! I tried the new versions out, but cannot connect at all, when the E2EE app is activated.

I opened a new issue #2223 for that.

**Comment by georgehrke** [comment]
@spackmat As pointed out in the release notes, you need the very latest pre-release versions of the clients:
https://github.com/nextcloud/end_to_end_encryption/releases/tag/v1.5.2-beta1

Android you can't test yet, but @tobiasKaminsky will release 3.13.0RC later this week.

What client did you try?

**Comment by spackmat** [comment]
Sorry, didn't post the correct link to my new issue: https://github.com/nextcloud/desktop/issues/2223

**Comment by georgehrke** [comment]
> What client did you try?

I just saw https://github.com/nextcloud/desktop/issues/2223
Let's wait for some feedback from our Desktop devs in that case.

**Comment by spackmat** [comment]
The log I posted there might be interesting: I am not that into the details, but I see that the client creates a new keypair and fails to upload the public key with a 409 repsonse. After that it looks as it gives up and the connection hangs i connecting state.

**Comment by spackmat** [comment]
For the record: The new issue was solved by executing a `php occ files:scan-app-data` command. After that the beta client connects and I could encrypt a test folder and copy files to it. When the Android preview is ready, I will test the interoperability with that.

**Comment by georgehrke** [comment]
We were no longer able to reproduce this issue with the latest set of clients / server app.
https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590

If you are still able to reproduce it, please speak up and we will reopen this issue.

**Comment by spackmat** [comment]
Yesterday, the Android beta came out and I can confirm that it works and is interoperable with the beta desktop client now, at least with my first tests. Thank you!
