### ISSUE TITLE
Add required check for NPM build back

### ISSUE THREAD

**Issue by kesselb** [nextcloud/end_to_end_encryption#719]
We run into some troubles with https://github.com/nextcloud/end_to_end_encryption/pull/709 and the "NPM build" check and therefore removed it temporary. 

The workflow https://github.com/nextcloud/end_to_end_encryption/blob/master/.github/workflows/node-when-unrelated.yml can be removed.

**Comment by artonge** [comment]
Required check added. Thanks.
