### ISSUE TITLE
Do not allow marking a non empty folder encrypted/unencrypted

### ISSUE THREAD

**Issue by rullzer** [nextcloud/end_to_end_encryption#76]
It would be good not to allow the encryption flag to be changed if the folder is not empty.

**Comment by tobiasKaminsky** [comment]
Good idea, currently this is also possible on android :fearful: 
@schiessle

**Comment by awesome-manuel** [comment]
See also https://github.com/nextcloud/client/issues/274

**Comment by awesome-manuel** [comment]
Also change https://github.com/nextcloud/end_to_end_encryption/blame/master/doc/api-usage.md#L24 and https://github.com/nextcloud/end_to_end_encryption/blame/master/doc/api-usage.md#L32.

**Comment by georgehrke** [comment]
@awesome-manuel That was a mistake in the `api-usage.md`. It's prohibited as per RFC.
See #130
