### ISSUE TITLE
Nextcloud 15 not supported

### ISSUE THREAD

**Issue by martincolladodotcom** [nextcloud/end_to_end_encryption#83]
I upgraded my nextcloud instance to the beta channel for testing Nextcloud 15b2. But the requierements for the end_to_end_encryption is Nextcloud <= 14. Any updates on that, any test that the app will be working with Nextcloud 15?.

Cheers

**Comment by MariusBluem** [comment]
Nextcloud 15 is in beta and this app was not updated in our App Store (available for Nextcloud 14 and 13 currently). The version on GitHub (development) is already tagged as compatible with Nextcloud 15 so you are welcome to test latest GitHub's `master`-version of End-to-End-Encryption together with Nextcloud 15 beta 2. Be careful - do not use it in production :)

With (or soon after) Nextcloud 15 is released, the End-to-End-Encryption app will be updated to support it.
