### ISSUE TITLE
E2E encryption not recursive with subdirectories

### ISSUE THREAD

**Issue by amastm** [nextcloud/end_to_end_encryption#86]
looks like encryption does not apply to nested folders inside an encrypted directory. Subdirectories should inherit the encryption from the upper level folder.

**Comment by tobiasKaminsky** [comment]
This should work.
On which device / platform do you experience this problem?

**Comment by tobiasKaminsky** [comment]
@camilasan is this supported?

**Comment by ad2003** [comment]
Hello! Anything new on this topic? I just tested out NC15 E2E. Having the same issues. I think it should be self-evident that everything within an encrytped folder should also be encrypted.

**Comment by tobiasKaminsky** [comment]
@camilasan ping :-)
At latest on our E2E Hackweek we should tackle this

**Comment by ad2003** [comment]
And I've got another one - when I use Windows Client and copy and paste files from an unencrypted subfolder to the encrypted mainfolder inside the PCs folders (not ftp) - those files were saved unencrypted on my server. IMHO there should be a small sign inside the clients app that clearly shows if a file is encrypted or not.

**Comment by ncodeyx** [comment]
Same issue here. Security risk in my case, glad I noticed it.

**Comment by larslehners** [comment]
Same issue here on Mac OSX 10.14.13  with nextcloud 2.5.1final (build 20181204)

**Comment by ncodeyx** [comment]
@tobiasKaminsky Any update?

**Comment by tobiasKaminsky** [comment]
@camilasan is currently on vacation, then we will discuss a roadmap, as some changes from Hackweek also needs to be implemented.

**Comment by KopfKrieg** [comment]
Quick question: Will there be any breaking changes? I've heard there will be a change in the way encryption works, but I'm not sure if this is true or not.

**Comment by tobiasKaminsky** [comment]
Yes, there will be a migration step needed: https://github.com/nextcloud/end_to_end_encryption_rfc/issues/34

**Comment by SonRiab** [comment]
There are several issues in the desktop repo discribing the problem already:
- nextcloud/desktop#774
- nextcloud/desktop#816
Mobile apps work as expected.

**Comment by ncodeyx** [comment]
So with what version should we expect this to be fixed?

**Comment by ncodeyx** [comment]
cc @tobiasKaminsky @camilasan

**Comment by tobiasKaminsky** [comment]
To not have this spread across multiple repos, I cloe this here, as
- this is the repo for the server app, not a "meta" E2E repo
- we have two bug reports in desktop (nextcloud/desktop#774, nextcloud/desktop#816)
- it works on mobile
