### ISSUE TITLE
User Agent check breaks E2E on Android

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/end_to_end_encryption#92]
Version 1.0.5 of the end_to_end_encryption app does not check the correct user agent for the (latest) Android Nextcloud App (version 3.4.0)

The checked user agent regex is `/^Mozilla\/5\.0 \(Android\) Nextcloud\-android.*$/`, while the app's actual user agent is `Mozilla/5.0 (Android) ownCloud-android/3.4.0`

Nextcloud version: 14.0.4 (latest stable)
E2E app version: 1.0.5 (latest from store)
Android Client version: 3.4.0 (latest from F-Droid)

**Comment by tobiasKaminsky** [comment]
Nextcloud Android app is using a new Nextcloud User agent for all E2E related methods only, while keep backward compatible for all other methods.

For example see: 
https://github.com/nextcloud/android/blob/21ebf1568e7ff54402bbd76ba83f3fccb1862e59/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java#L386-L387

last boolean is wether to use Nextcloud user agent.

**Comment by georgehrke** [comment]
Closing as per @tobiasKaminsky's explanation
