### ISSUE TITLE
Directory structure is leaked, not end to end encrypted

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/end_to_end_encryption#94]
The [promise on the official website for the end to end encryption reads as follows](https://nextcloud.com/endtoend/):

> Security properties: Never leak directory structure, filenames or file content to the server.

But currently, this is a lie. The [Nextcloud Desktop Client currently doesn't automatically encrypt subfolders of encrypted folders](https://github.com/nextcloud/desktop/issues/774), and even if I create subfolders using the Android App (which automatically encrypts subfolders of encrypted folders), the whole (!) directory structure is visible on the server. I can see every single folder in my so-called "end to end encrypted" folder.

This is a huge architectural flaw, leading to false promises and users who think their data is save even though it's not.

I'd like to open the discussion on how to approach the issue. End to end encryption is something I (personally) really want and need because some of my data is very sensitive. I currently see two options:
1. Either fix the current implementation, which probably breaks the current approach and might not be backwards compatible
2. Or integrate a different, already existing solution (like encfs, cryptomator or whatever) to address the issue

Another issue is the different code-base for desktop and mobile clients, which leads to the previously mentioned differences in the Android and Desktop app.

**Comment by jospoortvliet** [comment]
That is called 'a bug', my friend, we're sorry, but we're aware, and we will fix it.

**Comment by KopfKrieg** [comment]
Good to hear it's being worked on.

> It is not at all an architecture issue.

It's currently possible to have an unencrypted folder within an encrypted folder, and that data is leaked. IMHO that's an architectural issue (end to end encrypted folders shouldn't be able to leak *any* data in design terms, or not?).

**Comment by jospoortvliet** [comment]
> It's currently possible to have an unencrypted folder within an encrypted folder, and that data is leaked. IMHO that's an architectural issue (end to end encrypted folders shouldn't be able to leak any data in design terms, or not?).
That is possible because due to a bug subfolders aren't being encrypted. It was never meant to be that way, it wasn't designed that way - so isn't a problem in the design or architecture but the execution, that's what I was trying to say. Doesn't matter anyway, if our arch/RFC isn't clear enough on it, we have to fix that too of course. Next week, I have high expectations :+1:

**Comment by tobiasKaminsky** [comment]
There will be soon a version 2 of RFC.

**Comment by luixxiul** [comment]
> 
> 
> There will be soon a version 2 of RFC.

which is worked here: https://github.com/nextcloud/end_to_end_encryption_rfc/pull/40
