### ISSUE TITLE
cifrado de archivos falla

### ISSUE THREAD

**Issue by tmauricio** [nextcloud/end_to_end_encryption#95]
Habilite el cifrado punta a punta de archivos y me aparecio el siguiente mensaje: "No se ha cargado el modulo de cifrado. Por favor habilite un modulo de cifrado en el menú de aplicaciones."

Luego de ver ese mensaje me dispuse a agregar la aplicacion de cifrado que me faltaba instalar, y una vez instalada me sigue diciendo el mismo mensaje y ahora ni si quiera me deja destildar la encriptacion de archivos desde la configuración.

**Comment by tobiasKaminsky** [comment]
On which platform/device do you get this issue?

**Comment by tmauricio** [comment]
Error was solve! i was update the app and work fine!
