### ISSUE TITLE
High CPU cost in app.php

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/end_to_end_encryption#96]
The E2EE app registers an event listener for the "user deleted" hook. For this it needs the `KeyStorage` which is initialized in the register method. The constructor of the `KeyStorage` calls the method `checkFolderStructure()` which itself fetches the app data folder `/` and this operation is quite expensive - in our case it adds 170 ms to the whole request.

We should try to avoid such costly requests to each request and untangle the hooks a bit more. Hook registration should be super lightweight.

@schiessle Where is this `checkFolderStructure()` really needed? Can we move this somewhere else so that it is not executed on every request?

<img width="933" alt="bildschirmfoto 2019-01-21 um 11 13 18" src="https://user-images.githubusercontent.com/245432/51468169-94b4dd80-1d6e-11e9-9a24-4d86a472b0c2.png">

cc @nickvergessen @rullzer

**Comment by tobiasKaminsky** [comment]
Is this fixed?

**Comment by nickvergessen** [comment]
#97 removed like 20% of the total load, I guess there is more we could optimize, but not sure because i didnt install this app yet

**Comment by MorrisJobke** [comment]
Most of this is fixed in #97
